package com.chronos.education.scheduling.service;

import com.chronos.education.scheduling.dao.*;
import com.chronos.education.scheduling.model.*;
import com.chronos.education.scheduling.model.dto.CollaborationDtos.*;
import com.chronos.file.dao.ManagedFileRepository;
import com.chronos.commons.model.PageView;
import java.time.*; import java.util.*;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** 第二切片应用服务；只引用教务主数据，绝不创建平行教师/教学班/课表实体。 */
@Service @Transactional
public class TeachingCollaborationService {
 private final PreparationRepository preparations; private final PreparationMemberRepository members;
 private final PreparationMaterialRepository prepMaterials; private final PreparationCommentRepository comments;
 private final CoursewareRepository coursewares; private final CoursewareVersionRepository coursewareVersions;
 private final TeachingMaterialRepository materials; private final TeachingMaterialVersionRepository materialVersions;
 private final CourseOfferingRepository offerings; private final ScheduleEntryRepository schedules;
 private final EducationDataScopeService scopes; private final ManagedFileRepository files;
 public TeachingCollaborationService(PreparationRepository p,PreparationMemberRepository m,PreparationMaterialRepository pm,
   PreparationCommentRepository c,CoursewareRepository cw,CoursewareVersionRepository cv,TeachingMaterialRepository tm,
   TeachingMaterialVersionRepository tv,CourseOfferingRepository o,ScheduleEntryRepository s,EducationDataScopeService ds,
   ManagedFileRepository f) { preparations=p;members=m;prepMaterials=pm;comments=c;coursewares=cw;coursewareVersions=cv;
   materials=tm;materialVersions=tv;offerings=o;schedules=s;scopes=ds;files=f; }
 private CourseOffering offering(String id,Authentication a){ var o=offerings.findById(id).orElseThrow(()->new NoSuchElementException("教学任务不存在")); scopes.assertOfferingAccess(scopes.resolve(a.getName()),o); return o; }
 private void file(String id,Authentication a){ if(id==null||id.isBlank()||id.contains("/")||id.contains("\\")) throw new IllegalArgumentException("fileId无效");
   var f=files.findById(id).orElseThrow(()->new IllegalArgumentException("文件不存在")); if(!a.getName().equals(f.getOwnerUsername())&&!Set.of("ACTIVE","PENDING_BIND").contains(f.getStatus())) throw new IllegalArgumentException("文件不可绑定"); }
 public Preparation createPreparation(PreparationCreateRequest r,Authentication a){ var o=offering(r.offeringId(),a); if(r.scheduleEntryId()!=null){var e=schedules.findById(r.scheduleEntryId()).orElseThrow(); if(!o.getId().equals(e.getOfferingId())||!"PUBLISHED".equals(e.getStatus())) throw new IllegalArgumentException("只能关联本教学任务的已发布课表项");}
   var p=new Preparation(); p.setId(UUID.randomUUID().toString()); p.setOfferingId(o.getId());p.setCampusId(o.getCampusId());p.setOwnerTeacherId(o.getTeacherId());p.setScheduleEntryId(r.scheduleEntryId());p.setTitle(r.title());p.setPreparationType(r.preparationType());p.setCreateBy(a.getName());return preparations.save(p); }
 public Preparation getPreparation(String id,Authentication a){var p=preparations.findById(id).orElseThrow(); scopes.assertOfferingAccess(scopes.resolve(a.getName()),p.getOfferingId()); return p;}
 public PreparationMember invite(String id,MemberInviteRequest r,Authentication a){getPreparation(id,a); scopes.assertTeacherAccess(scopes.resolve(a.getName()),r.teacherId()); var m=new PreparationMember();m.setId(UUID.randomUUID().toString());m.setPreparationId(id);m.setTeacherId(r.teacherId());m.setRole(r.role());m.setInvitedBy(a.getName());m.setInvitedAt(Instant.now());return members.save(m);}
 public PreparationMember respond(String memberId,MemberResponseRequest r,Authentication a){var m=members.findById(memberId).orElseThrow();getPreparation(m.getPreparationId(),a); if(!Set.of("ACCEPT","DECLINE").contains(r.response())) throw new IllegalArgumentException("响应必须为ACCEPT或DECLINE");m.setInvitationStatus(r.response());m.setResponseComment(r.comment());m.setRespondedAt(Instant.now());return members.save(m);}
 public PreparationMaterial addMaterial(String id,MaterialRequest r,Authentication a){getPreparation(id,a);file(r.fileId(),a);var m=new PreparationMaterial();m.setId(UUID.randomUUID().toString());m.setPreparationId(id);m.setTitle(r.title());m.setFileId(r.fileId());m.setMetadataJson(r.metadataJson());m.setCreateBy(a.getName());m.setCreateTime(Instant.now());m.setBindState("PENDING_BIND");return prepMaterials.save(m);}
 public PreparationComment comment(String id,CommentRequest r,Authentication a){getPreparation(id,a);var c=new PreparationComment();c.setId(UUID.randomUUID().toString());c.setPreparationId(id);c.setAuthorId(a.getName());c.setContent(r.content());c.setCreateTime(Instant.now());c.setAuditAction("CREATE");return comments.save(c);}
 public Preparation conclude(String id,ConclusionRequest r,Authentication a){var p=getPreparation(id,a);p.setConclusion(r.conclusion());p.setConclusionLessonPlanId(r.lessonPlanId());p.setStatus("CONCLUDED");return preparations.save(p);}
 public Object createResource(boolean courseware,ResourceCreateRequest r,Authentication a){var o=offering(r.offeringId(),a);if(courseware){var x=new Courseware();x.setId(UUID.randomUUID().toString());x.setOfferingId(o.getId());x.setCampusId(o.getCampusId());x.setOwnerTeacherId(o.getTeacherId());x.setTitle(r.title());x.setShareScope(scope(r.shareScope()));x.setCreateBy(a.getName());return coursewares.save(x);}var x=new TeachingMaterial();x.setId(UUID.randomUUID().toString());x.setOfferingId(o.getId());x.setCampusId(o.getCampusId());x.setOwnerTeacherId(o.getTeacherId());x.setTitle(r.title());x.setMaterialType(r.materialType());x.setShareScope(scope(r.shareScope()));x.setCreateBy(a.getName());return materials.save(x);}
 private String scope(String s){return s==null||s.isBlank()?"PRIVATE":Set.of("PRIVATE","OFFERING","CAMPUS","PUBLIC").contains(s)?s: "PRIVATE";}
 public Object addVersion(boolean cw,String id,VersionRequest r,Authentication a){file(r.fileId(),a); int n;if(cw){var x=coursewares.findById(id).orElseThrow();scopes.assertOfferingAccess(scopes.resolve(a.getName()),x.getOfferingId());n=coursewareVersions.findByCoursewareIdOrderByVersionNoDesc(id).stream().findFirst().map(v->v.getVersionNo()+1).orElse(1);var v=new CoursewareVersion();v.setId(UUID.randomUUID().toString());v.setCoursewareId(id);v.setVersionNo(n);v.setFileId(r.fileId());v.setMetadataJson(r.metadataJson());v.setCreateBy(a.getName());v.setCreateTime(java.time.LocalDateTime.now());return coursewareVersions.save(v);}var x=materials.findById(id).orElseThrow();scopes.assertOfferingAccess(scopes.resolve(a.getName()),x.getOfferingId());n=materialVersions.findByMaterialIdOrderByVersionNoDesc(id).stream().findFirst().map(v->v.getVersionNo()+1).orElse(1);var v=new TeachingMaterialVersion();v.setId(UUID.randomUUID().toString());v.setMaterialId(id);v.setVersionNo(n);v.setFileId(r.fileId());v.setMetadataJson(r.metadataJson());v.setCreateBy(a.getName());v.setCreateTime(java.time.LocalDateTime.now());return materialVersions.save(v);}
 public Object transition(boolean cw,String versionId,String action,Authentication a){if(cw){var v=coursewareVersions.findById(versionId).orElseThrow();var x=coursewares.findById(v.getCoursewareId()).orElseThrow();scopes.assertOfferingAccess(scopes.resolve(a.getName()),x.getOfferingId());return transition(v,action);}var v=materialVersions.findById(versionId).orElseThrow();var x=materials.findById(v.getMaterialId()).orElseThrow();scopes.assertOfferingAccess(scopes.resolve(a.getName()),x.getOfferingId());return transition(v,action);}
 public List<?> versions(boolean cw,String id,Authentication a){if(cw){var x=coursewares.findById(id).orElseThrow();scopes.assertOfferingAccess(scopes.resolve(a.getName()),x.getOfferingId());return coursewareVersions.findByCoursewareIdOrderByVersionNoDesc(id);}var x=materials.findById(id).orElseThrow();scopes.assertOfferingAccess(scopes.resolve(a.getName()),x.getOfferingId());return materialVersions.findByMaterialIdOrderByVersionNoDesc(id);}
 public Object readPublished(boolean cw,String id,Authentication a){return versions(cw,id,a).stream().filter(v->"PUBLISHED".equals(cw?((CoursewareVersion)v).getStatus():((TeachingMaterialVersion)v).getStatus())).findFirst().orElse(null);}
 private <T> T transition(T v,String action){Instant now=Instant.now();if(v instanceof CoursewareVersion x){if("submit".equals(action))x.setStatus("SUBMITTED");else if("revise".equals(action))x.setStatus("DRAFT");else if("publish".equals(action)){x.setStatus("PUBLISHED");x.setPublishedAt(now);x.setBindState("BOUND");}else if("archive".equals(action)){x.setStatus("ARCHIVED");x.setArchivedAt(now);}else if("bind".equals(action)){x.setBindState("BOUND");x.setBoundAt(now);}return (T)coursewareVersions.save(x);}var x=(TeachingMaterialVersion)v;if("submit".equals(action))x.setStatus("SUBMITTED");else if("revise".equals(action))x.setStatus("DRAFT");else if("publish".equals(action)){x.setStatus("PUBLISHED");x.setPublishedAt(now);x.setBindState("BOUND");}else if("archive".equals(action))x.setStatus("ARCHIVED");else if("bind".equals(action)){x.setBindState("BOUND");x.setBoundAt(now);}return (T)materialVersions.save(x);}
 @Scheduled(fixedDelayString="${education.teaching.file-reconcile-ms:900000}") public void reconcilePendingFiles(){var cutoff=LocalDateTime.now().minusHours(24); for(var f:files.findTop100ByBusinessTypeAndBusinessIdIsNullAndStatusAndCreateTimeBeforeOrderByCreateTimeAsc("EDUCATION_TEACHING","PENDING_BIND",cutoff)){f.setStatus("EXPIRED");files.save(f);}}
}
