package com.chronos.workflow;

import com.chronos.Idao.workflow.*;
import com.chronos.Idao.form.IFormDefinitionRepository;
import com.chronos.form.FormService;
import com.chronos.model.form.*;
import com.chronos.model.workflow.*;
import com.chronos.service.iService.IAuditLogService;
import com.chronos.workflow.ai.WorkflowAiProvider;
import com.chronos.workflow.executor.WorkflowExecutorRegistry;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.LocalDateTime;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.springframework.data.domain.*;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class WorkflowService {
    private static final Set<String> NODE_TYPES=Set.of("START","APPROVAL","TASK","CONDITION","CC","END","SERVICE_TASK","HTTP_TASK","AGENT_TASK","MESSAGE_TASK");
    private static final Pattern CONDITION=Pattern.compile("^([A-Za-z][A-Za-z0-9_.]*)\\s*(==|!=|>=|<=|>|<)\\s*(.+)$");
    private final IWorkflowDefinitionRepository definitions; private final IWorkflowNodeRepository nodes;
    private final IWorkflowEdgeRepository edges; private final IWorkflowAiSettingRepository settings;
    private final IWorkflowReviewRepository reviews; private final IWorkflowInstanceRepository instances;
    private final IWorkflowTaskRepository tasks; private final List<WorkflowAiProvider> aiProviders;
    private final IFormDefinitionRepository formDefinitions;
    private final FlowableDeploymentService flowableDeployment;
    private final FormService formService;
    private final WorkflowAssigneeResolver assigneeResolver;
    private final WorkflowExecutorRegistry executorRegistry;
    private final IAuditLogService audit; private final ObjectMapper json = new ObjectMapper();
    public WorkflowService(IWorkflowDefinitionRepository definitions,IWorkflowNodeRepository nodes,IWorkflowEdgeRepository edges,
            IWorkflowAiSettingRepository settings,IWorkflowReviewRepository reviews,IWorkflowInstanceRepository instances,
            IWorkflowTaskRepository tasks,List<WorkflowAiProvider> aiProviders,IAuditLogService audit,IFormDefinitionRepository formDefinitions,FlowableDeploymentService flowableDeployment,FormService formService,WorkflowAssigneeResolver assigneeResolver,WorkflowExecutorRegistry executorRegistry){this.definitions=definitions;this.nodes=nodes;this.edges=edges;this.settings=settings;this.reviews=reviews;this.instances=instances;this.tasks=tasks;this.aiProviders=aiProviders;this.audit=audit;this.formDefinitions=formDefinitions;this.flowableDeployment=flowableDeployment;this.formService=formService;this.assigneeResolver=assigneeResolver;this.executorRegistry=executorRegistry;}

    public Page<WorkflowDefinition> list(Pageable pageable){return definitions.findAll(pageable);}
    public WorkflowDefinition get(String id){return requireDefinition(id);}
    public List<WorkflowDefinition> available(){return definitions.findByStatusOrderByFlowNameAsc("PUBLISHED");}
    public Map<String,Object> startForm(String flowId){WorkflowDefinition d=requireDefinition(flowId);if(!"PUBLISHED".equals(d.getStatus()))throw new IllegalArgumentException("流程未发布");if(d.getMainFormId()==null||d.getMainFormId().isBlank())return Map.of("flowId",d.getId(),"flowName",d.getFlowName(),"fields",List.of());FormDefinition form=formService.definition(d.getMainFormId());List<Map<String,Object>> schema=new ArrayList<>();for(FormField field:formService.fields(form.getId()))schema.add(Map.of("fieldKey",field.getFieldKey(),"fieldLabel",field.getFieldLabel(),"fieldType",field.getFieldType(),"required",Boolean.TRUE.equals(field.getRequired()),"permission","EDIT","optionsJson",field.getOptionsJson()==null?"[]":field.getOptionsJson()));return Map.of("flowId",d.getId(),"flowName",d.getFlowName(),"description",d.getDescription()==null?"":d.getDescription(),"formId",form.getId(),"formName",form.getFormName(),"fields",schema);}
    @Transactional public WorkflowDefinition save(WorkflowDefinition value,String actor){
        if(value.getFlowName()==null||value.getFlowName().isBlank())throw new IllegalArgumentException("流程名称不能为空");
        value.setFlowCode(required(value.getFlowCode(),"流程编码不能为空"));
        if(value.getVersion()==null||value.getVersion().isBlank())value.setVersion("v1");
        if(definitions.existsByFlowCodeAndVersion(value.getFlowCode(),value.getVersion()))throw new IllegalArgumentException("流程编码和版本已存在");
        validateJson(value.getStarterScopeJson(),"发起范围");
        validateForm(value.getMainFormId()); value.setStatus("DRAFT"); value.setPublishedAt(null); WorkflowDefinition saved=definitions.save(value);
        audit.log(actor,"WORKFLOW_DEFINITION_SAVE","flowId="+saved.getId()); return saved;
    }
    @Transactional public WorkflowDefinition update(WorkflowDefinition value,String actor){
        WorkflowDefinition old=requireDefinition(value.getId()); ensureDraft(old);
        old.setFlowName(required(value.getFlowName(),"流程名称不能为空")); old.setDescription(value.getDescription());old.setCategory(value.getCategory());
        old.setEntryNodeKey(value.getEntryNodeKey()); old.setTags(value.getTags()); old.setConfigJson(value.getConfigJson());
        old.setManagerUser(value.getManagerUser());validateJson(value.getStarterScopeJson(),"发起范围");old.setStarterScopeJson(value.getStarterScopeJson());
        validateForm(value.getMainFormId()); old.setMainFormId(value.getMainFormId());
        old.setAiAssistEnabled(Boolean.TRUE.equals(value.getAiAssistEnabled())); audit.log(actor,"WORKFLOW_DEFINITION_UPDATE","flowId="+old.getId()); return definitions.save(old);
    }
    @Transactional public void delete(String id,String actor){WorkflowDefinition d=requireDefinition(id);if("PUBLISHED".equals(d.getStatus()))throw new IllegalArgumentException("已发布流程不可删除，请停用或创建新版本");reviews.deleteByFlowId(id);edges.deleteByFlowId(id);nodes.deleteByFlowId(id);definitions.delete(d);audit.log(actor,"WORKFLOW_DEFINITION_DELETE","flowId="+id);}
    @Transactional public WorkflowDefinition disable(String id,String actor){WorkflowDefinition d=requireDefinition(id);if(!"PUBLISHED".equals(d.getStatus()))throw new IllegalArgumentException("只有已发布流程可以停用");d.setStatus("DISABLED");audit.log(actor,"WORKFLOW_DISABLE","flowId="+id);return definitions.save(d);}
    @Transactional public WorkflowDefinition createVersion(String id,String version,String actor){WorkflowDefinition source=requireDefinition(id);String next=required(version,"新版本号不能为空");if(definitions.existsByFlowCodeAndVersion(source.getFlowCode(),next))throw new IllegalArgumentException("该版本已存在");WorkflowDefinition d=new WorkflowDefinition();d.setFlowCode(source.getFlowCode());d.setFlowName(source.getFlowName());d.setCategory(source.getCategory());d.setVersion(next);d.setDescription(source.getDescription());d.setEntryNodeKey(source.getEntryNodeKey());d.setStatus("DRAFT");d.setTags(source.getTags());d.setConfigJson(source.getConfigJson());d.setMainFormId(source.getMainFormId());d.setManagerUser(source.getManagerUser());d.setStarterScopeJson(source.getStarterScopeJson());d.setAiAssistEnabled(source.getAiAssistEnabled());d=definitions.save(d);for(WorkflowNode n:nodes(id)){WorkflowNode copy=new WorkflowNode();copy.setFlowId(d.getId());copy.setNodeKey(n.getNodeKey());copy.setNodeName(n.getNodeName());copy.setNodeType(n.getNodeType());copy.setExecutor(n.getExecutor());copy.setTimeoutSec(n.getTimeoutSec());copy.setRetryMax(n.getRetryMax());copy.setRetryIntervalSec(n.getRetryIntervalSec());copy.setInputSchema(n.getInputSchema());copy.setOutputSchema(n.getOutputSchema());copy.setPropertiesJson(n.getPropertiesJson());copy.setAdditionalFormIds(n.getAdditionalFormIds());copy.setFieldPermissionsJson(n.getFieldPermissionsJson());nodes.save(copy);}for(WorkflowEdge e:edges(id)){WorkflowEdge copy=new WorkflowEdge();copy.setFlowId(d.getId());copy.setFromNodeKey(e.getFromNodeKey());copy.setToNodeKey(e.getToNodeKey());copy.setConditionExpr(e.getConditionExpr());copy.setIsDefault(e.getIsDefault());edges.save(copy);}audit.log(actor,"WORKFLOW_CREATE_VERSION","source="+id+", target="+d.getId()+", version="+next);return d;}
    public List<WorkflowNode> nodes(String flowId){requireDefinition(flowId);return nodes.findByFlowIdOrderByCreateTimeAsc(flowId);}
    public List<WorkflowEdge> edges(String flowId){requireDefinition(flowId);return edges.findByFlowIdOrderByCreateTimeAsc(flowId);}
    @Transactional public WorkflowNode saveNode(WorkflowNode value){WorkflowDefinition d=requireDefinition(value.getFlowId());ensureDraft(d);validateNode(value);return nodes.save(value);}
    @Transactional public WorkflowNode updateNode(WorkflowNode value){WorkflowNode old=nodes.findById(value.getId()).orElseThrow(()->new IllegalArgumentException("节点不存在"));ensureDraft(requireDefinition(old.getFlowId()));value.setFlowId(old.getFlowId());validateNode(value);old.setNodeKey(value.getNodeKey());old.setNodeName(value.getNodeName());old.setNodeType(value.getNodeType());old.setExecutor(value.getExecutor());old.setTimeoutSec(value.getTimeoutSec());old.setRetryMax(value.getRetryMax());old.setRetryIntervalSec(value.getRetryIntervalSec());old.setInputSchema(value.getInputSchema());old.setOutputSchema(value.getOutputSchema());old.setPropertiesJson(value.getPropertiesJson());old.setAdditionalFormIds(value.getAdditionalFormIds());old.setFieldPermissionsJson(value.getFieldPermissionsJson());return nodes.save(old);}
    @Transactional public void deleteNode(String id){WorkflowNode n=nodes.findById(id).orElseThrow(()->new IllegalArgumentException("节点不存在"));ensureDraft(requireDefinition(n.getFlowId()));edges.findByFlowIdOrderByCreateTimeAsc(n.getFlowId()).stream().filter(e->n.getNodeKey().equals(e.getFromNodeKey())||n.getNodeKey().equals(e.getToNodeKey())).forEach(edges::delete);nodes.delete(n);}
    @Transactional public WorkflowEdge saveEdge(WorkflowEdge value){ensureDraft(requireDefinition(value.getFlowId()));validateEdge(value);return edges.save(value);}
    @Transactional public WorkflowEdge updateEdge(WorkflowEdge value){WorkflowEdge old=edges.findById(value.getId()).orElseThrow(()->new IllegalArgumentException("连线不存在"));ensureDraft(requireDefinition(old.getFlowId()));value.setFlowId(old.getFlowId());validateEdge(value);old.setFromNodeKey(value.getFromNodeKey());old.setToNodeKey(value.getToNodeKey());old.setConditionExpr(value.getConditionExpr());old.setIsDefault(Boolean.TRUE.equals(value.getIsDefault()));return edges.save(old);}
    @Transactional public void deleteEdge(String id){WorkflowEdge e=edges.findById(id).orElseThrow(()->new IllegalArgumentException("连线不存在"));ensureDraft(requireDefinition(e.getFlowId()));edges.delete(e);}

    @Transactional public List<WorkflowReview> validate(String flowId,boolean includeAi,String actor){
        WorkflowDefinition d=requireDefinition(flowId);List<WorkflowNode> ns=nodes(flowId);List<WorkflowEdge> es=edges(flowId);
        reviews.deleteByFlowId(flowId);List<WorkflowReview> result=new ArrayList<>();Map<String,WorkflowNode> byKey=new LinkedHashMap<>();
        for(WorkflowNode n:ns){byKey.put(n.getNodeKey(),n);String type=upper(n.getNodeType());if(!NODE_TYPES.contains(type))result.add(finding(flowId,n.getId(),"RULE","HIGH","INVALID_NODE_TYPE","不支持的节点类型","允许类型："+NODE_TYPES,"修改节点类型",true,d,ns,es));if(Set.of("APPROVAL","TASK").contains(type)&&!hasAssignee(n))result.add(finding(flowId,n.getId(),"RULE","HIGH","ASSIGNEE_MISSING","处理人规则缺失","人工节点必须配置处理人规则","配置处理人",true,d,ns,es));if(Set.of("SERVICE_TASK","HTTP_TASK","AGENT_TASK","MESSAGE_TASK").contains(type)&&(n.getExecutor()==null||n.getExecutor().isBlank()))result.add(finding(flowId,n.getId(),"RULE","HIGH","EXECUTOR_MISSING","自动节点执行器未配置","自动节点尚不能运行","接通并选择可用执行器",true,d,ns,es));}
        if(ns.isEmpty())result.add(finding(flowId,null,"RULE","HIGH","EMPTY_FLOW","流程没有节点","至少需要开始和结束节点","添加节点",true,d,ns,es));
        long starts=ns.stream().filter(n->"START".equals(upper(n.getNodeType()))).count(),ends=ns.stream().filter(n->"END".equals(upper(n.getNodeType()))).count();if(starts!=1)result.add(finding(flowId,null,"RULE","HIGH","START_COUNT","开始节点数量不正确","必须且只能有一个开始节点","保留一个开始节点",true,d,ns,es));if(ends<1)result.add(finding(flowId,null,"RULE","HIGH","END_MISSING","缺少结束节点","至少需要一个结束节点","添加结束节点",true,d,ns,es));
        if(d.getEntryNodeKey()==null||!byKey.containsKey(d.getEntryNodeKey()))result.add(finding(flowId,null,"RULE","HIGH","ENTRY_MISSING","入口节点无效","入口节点必须指向现有节点","设置入口节点",true,d,ns,es));
        for(WorkflowEdge e:es){if(!byKey.containsKey(e.getFromNodeKey())||!byKey.containsKey(e.getToNodeKey()))result.add(finding(flowId,null,"RULE","HIGH","BROKEN_EDGE","连线引用了不存在的节点",e.getFromNodeKey()+" -> "+e.getToNodeKey(),"重新连接节点",true,d,ns,es));if(byKey.containsKey(e.getToNodeKey())&&"START".equals(upper(byKey.get(e.getToNodeKey()).getNodeType())))result.add(finding(flowId,null,"RULE","HIGH","START_INCOMING","开始节点不能有入线",e.getFromNodeKey()+" -> "+e.getToNodeKey(),"移除连线",true,d,ns,es));if(byKey.containsKey(e.getFromNodeKey())&&"END".equals(upper(byKey.get(e.getFromNodeKey()).getNodeType())))result.add(finding(flowId,null,"RULE","HIGH","END_OUTGOING","结束节点不能有出线",e.getFromNodeKey()+" -> "+e.getToNodeKey(),"移除连线",true,d,ns,es));if(e.getConditionExpr()!=null&&!e.getConditionExpr().isBlank()&&!CONDITION.matcher(e.getConditionExpr().trim()).matches())result.add(finding(flowId,null,"RULE","HIGH","INVALID_CONDITION","条件表达式不合法",e.getConditionExpr(),"使用 field >= value 格式",true,d,ns,es));}
        Map<String,List<WorkflowEdge>> outgoing=es.stream().collect(java.util.stream.Collectors.groupingBy(WorkflowEdge::getFromNodeKey));
        for(WorkflowNode n:ns)if(!"END".equals(upper(n.getNodeType()))&&outgoing.getOrDefault(n.getNodeKey(),List.of()).isEmpty())result.add(finding(flowId,n.getId(),"RULE","HIGH","DEAD_END","节点没有出口",n.getNodeName(),"连接后续节点或改为结束节点",true,d,ns,es));
        for(var entry:outgoing.entrySet())if(entry.getValue().stream().filter(e->Boolean.TRUE.equals(e.getIsDefault())||e.getConditionExpr()==null||e.getConditionExpr().isBlank()).count()>1)result.add(finding(flowId,byKey.containsKey(entry.getKey())?byKey.get(entry.getKey()).getId():null,"RULE","HIGH","MULTIPLE_DEFAULT_EDGES","节点存在多个默认出口",entry.getKey(),"只保留一个默认出口",true,d,ns,es));
        if(hasCycle(ns,es))result.add(finding(flowId,null,"RULE","HIGH","FLOW_CYCLE","流程存在循环通路","当前引擎不允许审批流程形成循环","移除回路，退回请使用节点退回规则",true,d,ns,es));
        if(d.getEntryNodeKey()!=null&&byKey.containsKey(d.getEntryNodeKey())){Set<String> reachable=reachable(d.getEntryNodeKey(),es);for(WorkflowNode n:ns)if(!reachable.contains(n.getNodeKey()))result.add(finding(flowId,n.getId(),"RULE","HIGH","UNREACHABLE_NODE","节点不可达",n.getNodeName(),"补充流程连线",true,d,ns,es));if(ns.stream().noneMatch(n->reachable.contains(n.getNodeKey())&&"END".equals(upper(n.getNodeType()))))result.add(finding(flowId,null,"RULE","HIGH","NO_END_PATH","流程没有可达的结束节点","流程可能无法结束","连接结束节点",true,d,ns,es));}
        if(includeAi){WorkflowAiSetting setting=setting();if(!Boolean.TRUE.equals(setting.getEnabled()))throw new IllegalArgumentException("AI辅助功能未开启");if(!Boolean.TRUE.equals(d.getAiAssistEnabled()))throw new IllegalArgumentException("当前流程未开启AI辅助");WorkflowAiProvider provider=provider(setting);if(provider==null)result.add(finding(flowId,null,"AI","MEDIUM","AI_PROVIDER_UNAVAILABLE","AI审查服务尚未接入","确定性检查已完成，未向外部服务发送数据","配置私有化AI Provider",false,d,ns,es));else for(var f:provider.review(d,ns,es))result.add(finding(flowId,f.nodeId(),"AI",f.severity(),f.category(),f.title(),f.description(),f.suggestion(),false,d,ns,es));}
        reviews.saveAll(result);audit.log(actor,"WORKFLOW_VALIDATE","flowId="+flowId+", ai="+includeAi+", findings="+result.size());return result;
    }
    @Transactional public WorkflowDefinition publish(String flowId,String actor){WorkflowDefinition d=requireDefinition(flowId);List<WorkflowReview> findings=validate(flowId,Boolean.TRUE.equals(d.getAiAssistEnabled())&&Boolean.TRUE.equals(setting().getEnabled()),actor);if(findings.stream().anyMatch(x->Boolean.TRUE.equals(x.getBlocking())))throw new IllegalArgumentException("流程存在阻断问题，不能发布");var deployed=flowableDeployment.deploy(d,nodes(flowId),edges(flowId));d.setFlowableDeploymentId(deployed.deploymentId());d.setFlowableProcessKey(deployed.processKey());d.setStatus("PUBLISHED");d.setPublishedAt(LocalDateTime.now());audit.log(actor,"WORKFLOW_PUBLISH","flowId="+flowId+", version="+d.getVersion()+", deployment="+deployed.deploymentId());return definitions.save(d);}

    public WorkflowAiSetting setting(){return settings.findAll().stream().findFirst().orElseGet(()->{WorkflowAiSetting s=new WorkflowAiSetting();s.setEnabled(false);s.setAllowExternal(false);s.setMaskSensitiveData(true);s.setProviderMode("LOCAL_PRIVATE");return settings.save(s);});}
    @Transactional public WorkflowAiSetting updateSetting(WorkflowAiSetting input,String actor){WorkflowAiSetting s=setting();s.setEnabled(Boolean.TRUE.equals(input.getEnabled()));s.setProviderMode(input.getProviderMode()==null?"LOCAL_PRIVATE":input.getProviderMode());s.setAllowExternal(Boolean.TRUE.equals(input.getAllowExternal()));s.setMaskSensitiveData(input.getMaskSensitiveData()==null||input.getMaskSensitiveData());audit.log(actor,"WORKFLOW_AI_SETTING_UPDATE","enabled="+s.getEnabled()+", mode="+s.getProviderMode()+", external="+s.getAllowExternal());return settings.save(s);}
    public Map<String,Object> aiDraft(String requirement){WorkflowAiSetting s=setting();if(!Boolean.TRUE.equals(s.getEnabled()))throw new IllegalArgumentException("AI辅助功能未开启");WorkflowAiProvider p=provider(s);if(p==null)throw new IllegalArgumentException("未配置可用的私有化AI Provider");return p.draft(required(requirement,"流程需求不能为空"));}

    @Transactional public WorkflowInstance start(String flowId,String businessKey,String variables,Map<String,Object> formData,String actor){WorkflowDefinition d=requireDefinition(flowId);if(!"PUBLISHED".equals(d.getStatus()))throw new IllegalArgumentException("只能发起已发布流程");WorkflowInstance i=new WorkflowInstance();i.setDefinitionId(d.getId());i.setDefinitionVersion(d.getVersion());i.setBusinessKey(businessKey);i.setInitiator(actor);i.setVariablesJson(variables==null?"{}":variables);i.setCurrentNodeKey(d.getEntryNodeKey());i=instances.save(i);if(d.getMainFormId()!=null&&!d.getMainFormId().isBlank()){Map<String,String> editable=new HashMap<>();for(FormField f:formService.fields(d.getMainFormId()))editable.put(d.getMainFormId()+"."+f.getFieldKey(),"EDIT");formService.saveRuntime(i.getId(),d.getMainFormId(),"_MAIN","MAIN",actor,formData==null?Map.of():formData,editable,Set.of(),false);}advance(i,d.getEntryNodeKey(),actor);audit.log(actor,"WORKFLOW_START","flowId="+flowId+", instanceId="+i.getId());return i;}
    public Map<String,Object> runtimeForms(String instanceId,String actor){WorkflowInstance instance=requireInstance(instanceId);ensureParticipant(instance,actor);WorkflowDefinition definition=requireDefinition(instance.getDefinitionId());WorkflowNode node=nodes.findByFlowIdAndNodeKey(definition.getId(),instance.getCurrentNodeKey()).orElseThrow(()->new IllegalArgumentException("当前节点不存在"));Map<String,String> permissions=permissionMap(node,"permissions");Set<String> required=permissionSet(node,"required");List<Map<String,Object>> forms=new ArrayList<>();if(definition.getMainFormId()!=null&&!definition.getMainFormId().isBlank())forms.add(runtimeForm(instance,definition.getMainFormId(),"_MAIN","MAIN",permissions,required));for(String id:additionalForms(node))forms.add(runtimeForm(instance,id,node.getNodeKey(),"ADDITIONAL",permissions,required));return Map.of("instanceId",instance.getId(),"nodeKey",node.getNodeKey(),"nodeName",node.getNodeName(),"forms",forms);}
    @Transactional public FormInstance saveRuntimeForm(String instanceId,String formId,Map<String,Object> data,boolean draft,String actor){WorkflowInstance instance=requireInstance(instanceId);ensureParticipant(instance,actor);WorkflowDefinition definition=requireDefinition(instance.getDefinitionId());WorkflowNode node=nodes.findByFlowIdAndNodeKey(definition.getId(),instance.getCurrentNodeKey()).orElseThrow(()->new IllegalArgumentException("当前节点不存在"));boolean main=Objects.equals(definition.getMainFormId(),formId);if(!main&&!additionalForms(node).contains(formId))throw new IllegalArgumentException("当前节点未绑定该表单");return formService.saveRuntime(instanceId,formId,main?"_MAIN":node.getNodeKey(),main?"MAIN":"ADDITIONAL",actor,data==null?Map.of():data,permissionMap(node,"permissions"),permissionSet(node,"required"),draft);}
    public List<WorkflowTask> pending(String actor){return tasks.findByAssigneeAndStatusOrderByCreateTimeDesc(actor,"PENDING");}
    @Transactional public WorkflowInstance completeTask(String taskId,boolean approved,String comment,String actor){WorkflowTask task=tasks.findById(taskId).orElseThrow(()->new IllegalArgumentException("任务不存在"));if(!actor.equals(task.getAssignee()))throw new AccessDeniedException("不是当前任务处理人");if(!"PENDING".equals(task.getStatus()))throw new IllegalArgumentException("任务已处理");WorkflowInstance i=instances.findById(task.getInstanceId()).orElseThrow();WorkflowNode node=nodes.findByFlowIdAndNodeKey(i.getDefinitionId(),task.getNodeKey()).orElseThrow();String mode=approvalMode(node);task.setStatus(approved?"APPROVED":"REJECTED");task.setComment(comment);task.setCompletedAt(LocalDateTime.now());tasks.save(task);List<WorkflowTask> siblings=tasks.findByInstanceIdOrderByCreateTimeAsc(i.getId()).stream().filter(t->t.getNodeKey().equals(task.getNodeKey())&&"PENDING".equals(t.getStatus())).toList();if(!approved){for(WorkflowTask sibling:siblings){sibling.setStatus("CANCELLED");sibling.setCompletedAt(LocalDateTime.now());tasks.save(sibling);}i.setStatus("REJECTED");i.setFinishedAt(LocalDateTime.now());}else if("ANY".equals(mode)){for(WorkflowTask sibling:siblings){sibling.setStatus("CANCELLED");sibling.setCompletedAt(LocalDateTime.now());tasks.save(sibling);}advance(i,task.getNodeKey(),actor);}else if(siblings.isEmpty())advance(i,task.getNodeKey(),actor);audit.log(actor,"WORKFLOW_TASK_COMPLETE","taskId="+taskId+", approved="+approved+", mode="+mode);return instances.save(i);}
    public List<WorkflowTask> handled(String actor){return tasks.findByAssigneeOrderByCreateTimeDesc(actor).stream().filter(t->!"PENDING".equals(t.getStatus())).toList();}
    public List<WorkflowInstance> initiated(String actor){return instances.findByInitiatorOrderByCreateTimeDesc(actor);}
    public Map<String,Object> monitor(){List<WorkflowInstance> all=instances.findAll();List<WorkflowTask> allTasks=tasks.findAll();LocalDateTime now=LocalDateTime.now();return Map.of("instances",all.size(),"running",all.stream().filter(i->"RUNNING".equals(i.getStatus())).count(),"completed",all.stream().filter(i->"COMPLETED".equals(i.getStatus())).count(),"rejected",all.stream().filter(i->"REJECTED".equals(i.getStatus())).count(),"pendingTasks",allTasks.stream().filter(t->"PENDING".equals(t.getStatus())).count(),"overdueTasks",allTasks.stream().filter(t->"PENDING".equals(t.getStatus())&&t.getDueAt()!=null&&t.getDueAt().isBefore(now)).count());}
    @Transactional public WorkflowTask remind(String taskId,String actor){WorkflowTask task=tasks.findById(taskId).orElseThrow(()->new IllegalArgumentException("任务不存在"));if(!"PENDING".equals(task.getStatus()))throw new IllegalArgumentException("仅待办任务可以催办");task.setRemindedAt(LocalDateTime.now());audit.log(actor,"WORKFLOW_TASK_REMIND","taskId="+taskId+", assignee="+task.getAssignee());return tasks.save(task);}
    @Transactional public void markOverdueTasks(){for(WorkflowTask task:tasks.findByStatusAndDueAtBefore("PENDING",LocalDateTime.now()))if(task.getRemindedAt()==null){task.setRemindedAt(LocalDateTime.now());tasks.save(task);audit.log("SYSTEM","WORKFLOW_TASK_OVERDUE","taskId="+task.getId()+", assignee="+task.getAssignee());}}
    @Transactional public WorkflowTask transferTask(String taskId,String assignee,String comment,String actor){WorkflowTask task=requirePendingTask(taskId,actor);String target=required(assignee,"转办人不能为空");task.setComment(operationComment("转办给 "+target,comment));task.setAssignee(target);audit.log(actor,"WORKFLOW_TASK_TRANSFER","taskId="+taskId+", target="+target);return tasks.save(task);}
    @Transactional public WorkflowTask addSign(String taskId,String assignee,String comment,String actor){WorkflowTask source=requirePendingTask(taskId,actor);WorkflowTask task=new WorkflowTask();task.setInstanceId(source.getInstanceId());task.setNodeKey(source.getNodeKey());task.setNodeName(source.getNodeName());task.setAssignee(required(assignee,"加签人不能为空"));task.setComment(operationComment("由 "+actor+" 加签",comment));audit.log(actor,"WORKFLOW_TASK_ADD_SIGN","taskId="+taskId+", assignee="+assignee);return tasks.save(task);}
    @Transactional public WorkflowTask ccTask(String taskId,String assignee,String comment,String actor){WorkflowTask source=requirePendingTask(taskId,actor);WorkflowTask task=new WorkflowTask();task.setInstanceId(source.getInstanceId());task.setNodeKey(source.getNodeKey());task.setNodeName(source.getNodeName()+"（抄送）");task.setAssignee(required(assignee,"抄送人不能为空"));task.setStatus("CC");task.setComment(operationComment("由 "+actor+" 抄送",comment));task.setCompletedAt(LocalDateTime.now());audit.log(actor,"WORKFLOW_TASK_CC","taskId="+taskId+", assignee="+assignee);return tasks.save(task);}
    @Transactional public WorkflowInstance returnTask(String taskId,String comment,String actor){WorkflowTask task=requirePendingTask(taskId,actor);WorkflowInstance instance=requireInstance(task.getInstanceId());List<WorkflowTask> history=tasks.findByInstanceIdOrderByCreateTimeAsc(instance.getId());WorkflowTask previous=null;for(WorkflowTask item:history)if(!item.getNodeKey().equals(task.getNodeKey())&&"APPROVED".equals(item.getStatus()))previous=item;if(previous==null)throw new IllegalArgumentException("没有可退回的上一人工节点");cancelPending(instance.getId(),operationComment("退回",comment));WorkflowNode target=nodes.findByFlowIdAndNodeKey(instance.getDefinitionId(),previous.getNodeKey()).orElseThrow();instance.setCurrentNodeKey(target.getNodeKey());instances.save(instance);createTask(instance,target,actor);audit.log(actor,"WORKFLOW_TASK_RETURN","taskId="+taskId+", target="+target.getNodeKey());return instance;}
    @Transactional public WorkflowInstance withdraw(String instanceId,String comment,String actor){WorkflowInstance instance=requireInstance(instanceId);if(!actor.equals(instance.getInitiator()))throw new AccessDeniedException("仅发起人可撤回");if(!"RUNNING".equals(instance.getStatus()))throw new IllegalArgumentException("当前状态不能撤回");cancelPending(instanceId,operationComment("发起人撤回",comment));instance.setStatus("WITHDRAWN");instance.setFinishedAt(LocalDateTime.now());audit.log(actor,"WORKFLOW_INSTANCE_WITHDRAW","instanceId="+instanceId);return instances.save(instance);}
    private WorkflowTask requirePendingTask(String id,String actor){WorkflowTask task=tasks.findById(id).orElseThrow(()->new IllegalArgumentException("任务不存在"));if(!"PENDING".equals(task.getStatus()))throw new IllegalArgumentException("任务已处理");if(!actor.equals(task.getAssignee()))throw new AccessDeniedException("不是当前任务处理人");return task;}
    private void cancelPending(String instanceId,String comment){for(WorkflowTask task:tasks.findByInstanceIdOrderByCreateTimeAsc(instanceId))if("PENDING".equals(task.getStatus())){task.setStatus("CANCELLED");task.setComment(comment);task.setCompletedAt(LocalDateTime.now());tasks.save(task);}}
    private String operationComment(String action,String comment){return comment==null||comment.isBlank()?action:action+"："+comment.trim();}

    private void advance(WorkflowInstance i,String from,String actor){WorkflowDefinition d=requireDefinition(i.getDefinitionId());WorkflowNode current=nodes.findByFlowIdAndNodeKey(d.getId(),from).orElseThrow(()->new IllegalArgumentException("当前节点不存在"));if("END".equals(upper(current.getNodeType()))){i.setStatus("COMPLETED");i.setFinishedAt(LocalDateTime.now());instances.save(i);return;}List<WorkflowEdge> outgoing=edges.findByFlowIdAndFromNodeKey(d.getId(),from);WorkflowEdge next=choose(outgoing,i.getVariablesJson());if(next==null){if("START".equals(upper(current.getNodeType())))throw new IllegalArgumentException("入口节点没有有效出口");i.setCurrentNodeKey(from);createTask(i,current,actor);return;}WorkflowNode target=nodes.findByFlowIdAndNodeKey(d.getId(),next.getToNodeKey()).orElseThrow();i.setCurrentNodeKey(target.getNodeKey());instances.save(i);String type=upper(target.getNodeType());if("END".equals(type)){i.setStatus("COMPLETED");i.setFinishedAt(LocalDateTime.now());instances.save(i);}else if(Set.of("START","CONDITION","CC").contains(type))advance(i,target.getNodeKey(),actor);else if(Set.of("SERVICE_TASK","HTTP_TASK","AGENT_TASK","MESSAGE_TASK").contains(type)){i.setVariablesJson(executorRegistry.execute(target,i.getVariablesJson()));instances.save(i);audit.log(actor,"WORKFLOW_AUTO_NODE","instanceId="+i.getId()+", node="+target.getNodeKey()+", executor="+target.getExecutor());advance(i,target.getNodeKey(),actor);}else createTask(i,target,actor);}
    private void createTask(WorkflowInstance i,WorkflowNode n,String actor){List<String> assignees=assigneeResolver.resolve(n,i,actor);if(assignees.isEmpty())throw new IllegalArgumentException("节点未解析到有效处理人："+n.getNodeName());if("SINGLE".equals(approvalMode(n)))assignees=assignees.subList(0,1);int dueHours=dueHours(n);for(String assignee:assignees){WorkflowTask t=new WorkflowTask();t.setInstanceId(i.getId());t.setNodeKey(n.getNodeKey());t.setNodeName(n.getNodeName());t.setAssignee(assignee);if(dueHours>0)t.setDueAt(LocalDateTime.now().plusHours(dueHours));tasks.save(t);}}
    private String resolveAssignee(WorkflowNode n,String actor){try{JsonNode p=json.readTree(n.getPropertiesJson()==null?"{}":n.getPropertiesJson());String v=p.path("assigneeValue").asText(p.path("assignee").asText());return "USER".equals(p.path("assigneeMode").asText("USER"))&&!v.isBlank()?v:actor;}catch(Exception e){return actor;}}
    private String approvalMode(WorkflowNode n){try{return json.readTree(n.getPropertiesJson()==null?"{}":n.getPropertiesJson()).path("approvalMode").asText("SINGLE");}catch(Exception e){return "SINGLE";}}
    private int dueHours(WorkflowNode n){try{return Math.max(0,json.readTree(n.getPropertiesJson()==null?"{}":n.getPropertiesJson()).path("dueHours").asInt(0));}catch(Exception e){return 0;}}
    private WorkflowEdge choose(List<WorkflowEdge> values,String variables){for(WorkflowEdge e:values)if(e.getConditionExpr()!=null&&!e.getConditionExpr().isBlank()&&matches(e.getConditionExpr(),variables))return e;return values.stream().filter(e->Boolean.TRUE.equals(e.getIsDefault())||e.getConditionExpr()==null||e.getConditionExpr().isBlank()).findFirst().orElse(null);}
    private boolean matches(String expr,String variables){try{Matcher m=CONDITION.matcher(expr.trim());if(!m.matches())return false;JsonNode v=json.readTree(variables==null?"{}":variables).path(m.group(1));String right=m.group(3).trim().replaceAll("^[\\\"']|[\\\"']$","");int c=v.isNumber()?Double.compare(v.asDouble(),Double.parseDouble(right)):v.asText().compareTo(right);return switch(m.group(2)){case "=="->c==0;case "!="->c!=0;case ">"->c>0;case "<"->c<0;case ">="->c>=0;case "<="->c<=0;default->false;};}catch(Exception e){return false;}}
    private WorkflowAiProvider provider(WorkflowAiSetting s){return aiProviders.stream().filter(p->p.mode().equalsIgnoreCase(s.getProviderMode())).filter(p->!p.external()||Boolean.TRUE.equals(s.getAllowExternal())).findFirst().orElse(null);}
    private boolean hasAssignee(WorkflowNode n){try{JsonNode p=json.readTree(n.getPropertiesJson()==null?"{}":n.getPropertiesJson());if("INITIATOR_MANAGER".equals(p.path("assigneeMode").asText()))return true;return !(p.path("assigneeValue").asText().isBlank()&&p.path("assignee").asText().isBlank()&&p.path("assigneeRoleCode").asText().isBlank()&&p.path("assigneeRule").asText().isBlank());}catch(Exception e){return false;}}
    private void validateNode(WorkflowNode n){required(n.getFlowId(),"flowId不能为空");required(n.getNodeKey(),"节点Key不能为空");required(n.getNodeName(),"节点名称不能为空");n.setNodeType(upper(required(n.getNodeType(),"节点类型不能为空")));if(!NODE_TYPES.contains(n.getNodeType()))throw new IllegalArgumentException("不支持的节点类型");validateJson(n.getPropertiesJson(),"节点扩展配置");validateJson(n.getAdditionalFormIds(),"附加表单");validateJson(n.getFieldPermissionsJson(),"字段权限");try{for(JsonNode id:json.readTree(n.getAdditionalFormIds()==null?"[]":n.getAdditionalFormIds()))validateForm(id.asText());}catch(IllegalArgumentException e){throw e;}catch(Exception e){throw new IllegalArgumentException("附加表单不是合法JSON");}}
    private void validateForm(String id){if(id!=null&&!id.isBlank()&&!formDefinitions.existsById(id))throw new IllegalArgumentException("引用的表单不存在");}
    private void validateJson(String value,String label){if(value!=null&&!value.isBlank())try{json.readTree(value);}catch(Exception e){throw new IllegalArgumentException(label+"不是合法JSON");}}
    private void validateEdge(WorkflowEdge e){required(e.getFlowId(),"flowId不能为空");if(nodes.findByFlowIdAndNodeKey(e.getFlowId(),e.getFromNodeKey()).isEmpty()||nodes.findByFlowIdAndNodeKey(e.getFlowId(),e.getToNodeKey()).isEmpty())throw new IllegalArgumentException("连线节点不存在");if(Objects.equals(e.getFromNodeKey(),e.getToNodeKey()))throw new IllegalArgumentException("节点不能直接连接自身");if(Boolean.TRUE.equals(e.getIsDefault())&&edges.findByFlowIdAndFromNodeKey(e.getFlowId(),e.getFromNodeKey()).stream().anyMatch(x->Boolean.TRUE.equals(x.getIsDefault())&&!Objects.equals(x.getId(),e.getId())))throw new IllegalArgumentException("同一节点只能配置一条默认分支");if(!Boolean.TRUE.equals(e.getIsDefault())&&e.getConditionExpr()!=null&&!e.getConditionExpr().isBlank()&&!CONDITION.matcher(e.getConditionExpr().trim()).matches())throw new IllegalArgumentException("条件表达式不合法");}
    private Set<String> reachable(String start,List<WorkflowEdge> es){Map<String,List<String>> g=new HashMap<>();for(WorkflowEdge e:es)g.computeIfAbsent(e.getFromNodeKey(),k->new ArrayList<>()).add(e.getToNodeKey());Set<String> seen=new HashSet<>();Deque<String> q=new ArrayDeque<>();q.add(start);while(!q.isEmpty()){String x=q.remove();if(seen.add(x))q.addAll(g.getOrDefault(x,List.of()));}return seen;}
    private boolean hasCycle(List<WorkflowNode> ns,List<WorkflowEdge> es){Map<String,Integer> degree=new HashMap<>();Map<String,List<String>> graph=new HashMap<>();for(WorkflowNode n:ns)degree.put(n.getNodeKey(),0);for(WorkflowEdge e:es)if(degree.containsKey(e.getFromNodeKey())&&degree.containsKey(e.getToNodeKey())){graph.computeIfAbsent(e.getFromNodeKey(),k->new ArrayList<>()).add(e.getToNodeKey());degree.put(e.getToNodeKey(),degree.get(e.getToNodeKey())+1);}Deque<String> q=new ArrayDeque<>();degree.forEach((k,v)->{if(v==0)q.add(k);});int visited=0;while(!q.isEmpty()){String x=q.remove();visited++;for(String y:graph.getOrDefault(x,List.of()))if(degree.compute(y,(k,v)->v-1)==0)q.add(y);}return visited<degree.size();}
    private WorkflowReview finding(String f,String n,String source,String severity,String category,String title,String desc,String suggestion,boolean blocking,WorkflowDefinition d,List<WorkflowNode> ns,List<WorkflowEdge> es){WorkflowReview r=new WorkflowReview();r.setFlowId(f);r.setNodeId(n);r.setSource(source);r.setSeverity(severity);r.setCategory(category);r.setTitle(title);r.setDescription(desc);r.setSuggestion(suggestion);r.setBlocking(blocking);r.setConfigHash(hash(d,ns,es));return r;}
    private String hash(WorkflowDefinition d,List<WorkflowNode> ns,List<WorkflowEdge> es){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(json.writeValueAsString(List.of(d,ns,es)).getBytes(StandardCharsets.UTF_8)));}catch(Exception e){return "";}}
    private WorkflowDefinition requireDefinition(String id){return definitions.findById(id).orElseThrow(()->new IllegalArgumentException("流程不存在"));}
    private WorkflowInstance requireInstance(String id){return instances.findById(id).orElseThrow(()->new IllegalArgumentException("流程实例不存在"));}
    private void ensureParticipant(WorkflowInstance instance,String actor){boolean assignee=tasks.findByInstanceIdOrderByCreateTimeAsc(instance.getId()).stream().anyMatch(t->"PENDING".equals(t.getStatus())&&actor.equals(t.getAssignee()));if(!actor.equals(instance.getInitiator())&&!assignee)throw new AccessDeniedException("无权访问该流程表单");}
    private List<String> additionalForms(WorkflowNode node){try{List<String> values=new ArrayList<>();for(JsonNode id:json.readTree(node.getAdditionalFormIds()==null?"[]":node.getAdditionalFormIds()))values.add(id.asText());return values;}catch(Exception e){return List.of();}}
    private Map<String,String> permissionMap(WorkflowNode node,String field){try{Map<String,String> values=new HashMap<>();json.readTree(node.getFieldPermissionsJson()==null?"{}":node.getFieldPermissionsJson()).path(field).fields().forEachRemaining(e->values.put(e.getKey(),e.getValue().asText()));return values;}catch(Exception e){return Map.of();}}
    private Set<String> permissionSet(WorkflowNode node,String field){try{Set<String> values=new HashSet<>();json.readTree(node.getFieldPermissionsJson()==null?"{}":node.getFieldPermissionsJson()).path(field).fields().forEachRemaining(e->{if(e.getValue().asBoolean())values.add(e.getKey());});return values;}catch(Exception e){return Set.of();}}
    private Map<String,Object> runtimeForm(WorkflowInstance instance,String formId,String nodeKey,String role,Map<String,String> permissions,Set<String> required){FormDefinition definition=formService.definition(formId);List<Map<String,Object>> schema=new ArrayList<>();for(FormField field:formService.fields(formId)){String key=formId+"."+field.getFieldKey();String permission=permissions.getOrDefault(key,"READ");if(!"HIDDEN".equals(permission))schema.add(Map.of("fieldKey",field.getFieldKey(),"fieldLabel",field.getFieldLabel(),"fieldType",field.getFieldType(),"required",required.contains(key),"permission",permission,"optionsJson",field.getOptionsJson()==null?"[]":field.getOptionsJson()));}Map<String,Object> data=formService.instance(instance.getId(),formId,nodeKey).map(x->{try{return json.readValue(x.getDataJson(),new com.fasterxml.jackson.core.type.TypeReference<Map<String,Object>>(){});}catch(Exception e){return Map.<String,Object>of();}}).orElse(Map.of());return Map.of("formId",formId,"formName",definition.getFormName(),"role",role,"fields",schema,"data",data);}
    private void ensureDraft(WorkflowDefinition d){if(!"DRAFT".equals(d.getStatus()))throw new IllegalArgumentException("只有草稿流程可以修改");}
    private String required(String v,String message){if(v==null||v.isBlank())throw new IllegalArgumentException(message);return v.trim();}
    private String upper(String v){return v==null?"":v.trim().toUpperCase();}
}
