package com.chronos.education.grade.controller;
import com.chronos.commons.model.ResultData; import com.chronos.education.grade.dto.GradeDtos.*; import com.chronos.education.grade.model.*; import com.chronos.education.grade.service.GradeCenterService; import java.util.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/admin/education/grades") public class GradeCenterController { private final GradeCenterService service; public GradeCenterController(GradeCenterService service){this.service=service;}
 @GetMapping("/schemes") @PreAuthorize("@iamAuthorization.any(authentication,'education:score:scheme:view','education:score:scheme:manage')") public ResultData<List<AssessmentScheme>> schemes(@RequestParam(required=false) String offeringId){return ok(service.listSchemes(offeringId));}
 @PostMapping("/schemes") @PreAuthorize("@iamAuthorization.any(authentication,'education:score:scheme:manage')") public ResultData<AssessmentScheme> create(@RequestBody SchemeCommand c,Authentication a){return ok(service.createScheme(c,a.getName()));}
 @PostMapping("/schemes/{id}/publish") @PreAuthorize("@iamAuthorization.any(authentication,'education:score:scheme:publish','education:score:scheme:manage')") public ResultData<AssessmentScheme> publishScheme(@PathVariable String id,Authentication a){return ok(service.publishScheme(id,a.getName()));}
 @GetMapping("/gradebooks/{id}") @PreAuthorize("@iamAuthorization.any(authentication,'education:score:gradebook:view','education:score:gradebook:manage')") public ResultData<Gradebook> gradebook(@PathVariable String id,Authentication a){return ok(service.getGradebook(id,a.getName()));}
 @GetMapping("/gradebooks") @PreAuthorize("@iamAuthorization.any(authentication,'education:score:gradebook:view','education:score:gradebook:manage')") public ResultData<List<Gradebook>> gradebooks(Authentication a){return ok(service.listGradebooks(a.getName()));}
 @PostMapping("/gradebooks") @PreAuthorize("@iamAuthorization.any(authentication,'education:score:gradebook:manage')") public ResultData<Gradebook> createGradebook(@RequestBody GradebookCommand c,Authentication a){return ok(service.createGradebook(c,a.getName()));}
 @PutMapping("/gradebooks/{id}/items") @PreAuthorize("@iamAuthorization.any(authentication,'education:score:gradebook:entry','education:score:gradebook:manage')") public ResultData<Gradebook> items(@PathVariable String id,@RequestBody ItemsCommand c,Authentication a){return ok(service.saveItems(id,c,a.getName()));}
 @PostMapping("/gradebooks/{id}/submit") @PreAuthorize("@iamAuthorization.any(authentication,'education:score:gradebook:submit','education:score:gradebook:manage')") public ResultData<Gradebook> submit(@PathVariable String id,Authentication a){return ok(service.submit(id,a.getName()));}
 @PostMapping("/gradebooks/{id}/review") @PreAuthorize("@iamAuthorization.any(authentication,'education:score:gradebook:review')") public ResultData<Gradebook> review(@PathVariable String id,@RequestParam String taskId,@RequestParam boolean approved,@RequestParam(required=false) String comment,Authentication a){return ok(service.review(id,taskId,approved,comment,a.getName()));}
 @PostMapping("/gradebooks/{id}/publish") @PreAuthorize("@iamAuthorization.any(authentication,'education:score:gradebook:publish')") public ResultData<Gradebook> publish(@PathVariable String id,Authentication a){return ok(service.publish(id,a.getName()));}
 private <T> ResultData<T> ok(T data){return ResultData.<T>builder().code("200").msg("ok").data(data).build();}
}
