-- 分支合并后顺延版本，避免与既有 V20261202 冲突。
CREATE TABLE IF NOT EXISTS int_connector (id varchar(64) PRIMARY KEY, create_by varchar(128) NOT NULL, create_time timestamp NOT NULL, last_update_by varchar(128), last_update_time timestamp, name varchar(120) NOT NULL, type varchar(30) NOT NULL, base_url varchar(1000) NOT NULL, status varchar(20) NOT NULL, timeout_ms integer NOT NULL, max_retries integer NOT NULL, config_json text NOT NULL);
CREATE TABLE IF NOT EXISTS int_credential (id varchar(64) PRIMARY KEY, create_by varchar(128) NOT NULL, create_time timestamp NOT NULL, last_update_by varchar(128), last_update_time timestamp, connector_id varchar(64) NOT NULL, key_name varchar(120) NOT NULL, secret_ciphertext text NOT NULL);
CREATE TABLE IF NOT EXISTS int_sync_job (id varchar(64) PRIMARY KEY, create_by varchar(128) NOT NULL, create_time timestamp NOT NULL, last_update_by varchar(128), last_update_time timestamp, name varchar(160) NOT NULL, connector_id varchar(64) NOT NULL, cron_expression varchar(100) NOT NULL, status varchar(20) NOT NULL, request_path varchar(500) NOT NULL, idempotency_key_template varchar(300), lease_owner varchar(120), lease_until timestamp);
CREATE TABLE IF NOT EXISTS int_sync_run (id varchar(64) PRIMARY KEY, create_by varchar(128) NOT NULL, create_time timestamp NOT NULL, last_update_by varchar(128), last_update_time timestamp, job_id varchar(64) NOT NULL, status varchar(20) NOT NULL, started_at timestamp NOT NULL, finished_at timestamp, success_count integer NOT NULL DEFAULT 0, failure_count integer NOT NULL DEFAULT 0, attempt_count integer NOT NULL DEFAULT 0, error_message text);
CREATE TABLE IF NOT EXISTS int_sync_item_error (id varchar(64) PRIMARY KEY, create_by varchar(128) NOT NULL, create_time timestamp NOT NULL, last_update_by varchar(128), last_update_time timestamp, run_id varchar(64) NOT NULL, item_key varchar(300) NOT NULL, payload_json text, error_message text NOT NULL, status varchar(20) NOT NULL, attempt_count integer NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS int_dead_letter (id varchar(64) PRIMARY KEY, create_by varchar(128) NOT NULL, create_time timestamp NOT NULL, last_update_by varchar(128), last_update_time timestamp, item_error_id varchar(64) NOT NULL, run_id varchar(64) NOT NULL, replay_count integer NOT NULL DEFAULT 0, status varchar(20) NOT NULL, last_result text, replayed_at timestamp);
CREATE INDEX IF NOT EXISTS idx_int_run_job ON int_sync_run(job_id,started_at); CREATE INDEX IF NOT EXISTS idx_int_error_run ON int_sync_item_error(run_id); CREATE INDEX IF NOT EXISTS idx_int_dead_status ON int_dead_letter(status);
INSERT INTO t_permission(id,create_by,create_time,permission_code,permission_name,permission_type,action_type,built_in,status) SELECT gen_random_uuid()::text,'SYSTEM',CURRENT_TIMESTAMP,v.code,v.name,'MENU_ACTION','MANAGE',true,1 FROM (VALUES ('integration:connector:view','查看集成连接器'),('integration:connector:manage','管理集成连接器'),('integration:connector:test','测试集成连接器'),('integration:job:view','查看同步任务'),('integration:job:manage','管理同步任务'),('integration:job:run','运行同步任务'),('integration:run:view','查看同步运行'),('integration:error:view','查看单条错误'),('integration:dead-letter:view','查看死信'),('integration:dead-letter:replay','重放死信')) v(code,name) WHERE NOT EXISTS (SELECT 1 FROM t_permission p WHERE p.permission_code=v.code);
