package com.chronos.education.grade.service;

import com.chronos.education.grade.dao.*;
import com.chronos.education.grade.dto.GradeDtos.*;
import com.chronos.education.grade.model.*;
import com.chronos.education.scheduling.dao.*;
import com.chronos.education.scheduling.model.*;
import com.chronos.service.iService.IAuditLogService;
import com.chronos.workflow.WorkflowService;
import com.chronos.Idao.workflow.IWorkflowTaskRepository;
import com.chronos.Idao.workflow.IWorkflowInstanceRepository;
import com.chronos.model.workflow.WorkflowTask;
import com.chronos.education.scheduling.service.EducationDataScopeService;
import org.springframework.security.access.AccessDeniedException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.LocalDateTime; import java.util.*; import java.util.stream.Collectors;

/** 成绩中心第一交付切片：仅允许 MANUAL 成绩项目，所有状态转换在事务内完成。 */
@Service
public class GradeCenterService {
 private final AssessmentSchemeRepository schemes; private final AssessmentComponentRepository components; private final GradebookRepository gradebooks; private final GradebookStudentRepository students; private final GradeItemRepository items; private final CourseGradeRepository courseGrades; private final GradePublishSnapshotRepository snapshots; private final CourseOfferingRepository offerings; private final TeachingClassMemberRepository members; private final StudentProfileRepository profiles; private final WorkflowService workflows; private final IWorkflowTaskRepository workflowTasks; private final IWorkflowInstanceRepository workflowInstances; private final EducationDataScopeService dataScopes; private final GradeNotificationService notifications; private final IAuditLogService audit; private final ObjectMapper json;
 public GradeCenterService(AssessmentSchemeRepository schemes,AssessmentComponentRepository components,GradebookRepository gradebooks,GradebookStudentRepository students,GradeItemRepository items,CourseGradeRepository courseGrades,GradePublishSnapshotRepository snapshots,CourseOfferingRepository offerings,TeachingClassMemberRepository members,StudentProfileRepository profiles,WorkflowService workflows,IWorkflowTaskRepository workflowTasks,IWorkflowInstanceRepository workflowInstances,EducationDataScopeService dataScopes,GradeNotificationService notifications,IAuditLogService audit,ObjectMapper json){this.schemes=schemes;this.components=components;this.gradebooks=gradebooks;this.students=students;this.items=items;this.courseGrades=courseGrades;this.snapshots=snapshots;this.offerings=offerings;this.members=members;this.profiles=profiles;this.workflows=workflows;this.workflowTasks=workflowTasks;this.workflowInstances=workflowInstances;this.dataScopes=dataScopes;this.notifications=notifications;this.audit=audit;this.json=json;}
 @Transactional(readOnly=true) public List<AssessmentScheme> listSchemes(String offeringId){return offeringId==null?schemes.findAll():schemes.findByOfferingIdOrderByCreateTimeDesc(offeringId);}
 @Transactional(readOnly=true) public List<Gradebook> listGradebooks(String actor){return dataScopes.resolve(actor).teacherIds().stream().flatMap(id->gradebooks.findByTeacherIdOrderByCreateTimeDesc(id).stream()).toList();}
 @Transactional public AssessmentScheme createScheme(SchemeCommand c,String actor){validateScheme(c); CourseOffering o=authorizedOffering(c.offeringId(),actor); AssessmentScheme s=new AssessmentScheme(); s.setSchoolId(serverSchoolId(actor));s.setOfferingId(o.getId());s.setName(c.name());s.setTotalScore(c.totalScore());s.setPassScore(c.passScore());s.setStatus("DRAFT");s=schemes.save(s); int order=0; for(ComponentCommand x:c.components()){AssessmentComponent a=new AssessmentComponent();a.setSchemeId(s.getId());a.setCode(x.code());a.setName(x.name());a.setSourceType(x.sourceType());a.setWeight(x.weight());a.setMaxScore(x.maxScore());a.setSortOrder(x.sortOrder()==null?order++:x.sortOrder());components.save(a);} audit.log(actor,"EDU_GRADE_SCHEME_CREATE","schemeId="+s.getId()); return s;}
 @Transactional public AssessmentScheme publishScheme(String id,String actor){AssessmentScheme s=schemes.findById(id).orElseThrow(); authorizedOffering(s.getOfferingId(),actor); validateWeights(components.findBySchemeIdOrderBySortOrder(id)); s.setStatus("PUBLISHED");s.setPublishedVersionNo(1); audit.log(actor,"EDU_GRADE_SCHEME_PUBLISH","schemeId="+id);return schemes.save(s);}
 @Transactional public Gradebook createGradebook(GradebookCommand c,String actor){CourseOffering o=authorizedOffering(c.offeringId(),actor);AssessmentScheme s=schemes.findById(c.schemeId()).orElseThrow();if(!"PUBLISHED".equals(s.getStatus())||!s.getOfferingId().equals(o.getId()))throw new IllegalArgumentException("只能使用本课程已发布方案");if(gradebooks.findByOfferingIdAndSchemeId(c.offeringId(),c.schemeId()).isPresent())throw new IllegalStateException("该课程已有成绩册");Gradebook g=new Gradebook();g.setSchoolId(serverSchoolId(actor));g.setOfferingId(o.getId());g.setSchemeId(s.getId());g.setTeacherId(o.getTeacherId());g.setStatus("EDITING");g=gradebooks.save(g);for(TeachingClassMember m:members.findByOfferingIdAndEnrollmentStatus(o.getId(),"ENROLLED")){var p=profiles.findById(m.getStudentId()).orElse(null);if(p==null)continue;GradebookStudent gs=new GradebookStudent();gs.setGradebookId(g.getId());gs.setStudentId(p.getId());gs.setStudentNo(p.getStudentNo());gs.setStudentName(p.getStudentName());gs.setAdministrativeClassId(p.getAdministrativeClassId());gs.setEnrollmentStatus(m.getEnrollmentStatus());gs.setSourceMemberId(m.getId());gs.setEnrolledAt(m.getEnrolledAt());gs.setWithdrawnAt(m.getWithdrawnAt());gs.setSnapshotHash(hash(snapshotStudent(gs)));students.save(gs);}audit.log(actor,"EDU_GRADEBOOK_CREATE","gradebookId="+g.getId());return g;}
 @Transactional(readOnly=true) public Gradebook getGradebook(String id,String actor){return authorizedGradebook(id,actor);}
 @Transactional public Gradebook saveItems(String id,ItemsCommand command,String actor){Gradebook g=authorizedGradebook(id,actor);if(!Set.of("EDITING","REJECTED").contains(g.getStatus()))throw new IllegalStateException("当前状态不可录入");if(command.rowVersion()!=null&&!command.rowVersion().equals(g.getRowVersion()))throw new org.springframework.orm.ObjectOptimisticLockingFailureException(Gradebook.class,id);List<AssessmentComponent> allowed=components.findBySchemeIdOrderBySortOrder(g.getSchemeId());Map<String,AssessmentComponent> byId=allowed.stream().collect(Collectors.toMap(AssessmentComponent::getId,x->x));List<GradebookStudent> roster=students.findByGradebookId(id);for(GradeItemCommand c:command.items()){AssessmentComponent component=byId.get(c.componentId());if(component==null)throw new IllegalArgumentException("成绩项目不属于当前成绩册方案");if(c.rawScore()!=null&&(c.rawScore().signum()<0||c.rawScore().compareTo(component.getMaxScore())>0))throw new IllegalArgumentException("成绩超出项目满分");if(roster.stream().noneMatch(x->x.getStudentId().equals(c.studentId())))throw new IllegalArgumentException("学生不在成绩册快照");GradeItem item=items.findByGradebookId(id).stream().filter(x->x.getComponentId().equals(c.componentId())&&x.getStudentId().equals(c.studentId())).findFirst().orElseGet(GradeItem::new);item.setGradebookId(id);item.setComponentId(c.componentId());item.setStudentId(c.studentId());item.setRawScore(c.rawScore());item.setConvertedScore(c.rawScore());item.setSpecialStatus(c.specialStatus());item.setRemark(c.remark());items.save(item);}return g;}
 @Transactional public Gradebook submit(String id,String actor){Gradebook g=authorizedGradebook(id,actor);if(!Set.of("EDITING","REJECTED").contains(g.getStatus()))throw new IllegalStateException("成绩册不可提交");if(items.findByGradebookId(id).isEmpty())throw new IllegalArgumentException("请先录入成绩");g.setSubmissionNo(g.getSubmissionNo()+1);g.setSubmittedAt(LocalDateTime.now());g.setStatus("REVIEWING");var instance=workflows.startByCode("EDU_GRADEBOOK_REVIEW",id,Map.<String,Object>of("gradebookId",id,"submitter",actor),actor);g.setWorkflowInstanceId(instance.getId());audit.log(actor,"EDU_GRADEBOOK_SUBMIT","gradebookId="+id);return gradebooks.save(g);}
 @Transactional public Gradebook review(String id,String taskId,boolean approved,String comment,String actor){Gradebook g=authorizedGradebook(id,actor);WorkflowTask task=workflowTasks.findById(taskId).orElseThrow(()->new IllegalArgumentException("审核任务不存在"));if(!id.equals(workflows.instance(task.getInstanceId()).getBusinessKey()))throw new AccessDeniedException("审核任务不属于当前成绩册");if(dataScopes.resolve(actor).teacherIds().contains(g.getTeacherId()))throw new AccessDeniedException("提交人不得审核本人成绩册");var instance=approved?workflows.completeTask(taskId,true,comment,actor):workflows.rejectTask(taskId,"",comment,actor);if("COMPLETED".equals(instance.getStatus()))g.setStatus("APPROVED");else if("REJECTED".equals(instance.getStatus()))g.setStatus("REJECTED");else g.setStatus("REVIEWING");audit.log(actor,approved?"EDU_GRADEBOOK_APPROVE":"EDU_GRADEBOOK_REJECT","gradebookId="+id+",node="+task.getNodeKey());return gradebooks.save(g);}
 @Transactional public Gradebook publish(String id,String actor){Gradebook g=authorizedGradebook(id,actor);if(!"APPROVED".equals(g.getStatus()))throw new IllegalStateException("仅审核通过后可发布");List<GradebookStudent> ss=students.findByGradebookId(id);List<AssessmentComponent> cs=components.findBySchemeIdOrderBySortOrder(g.getSchemeId());Map<String,List<GradeItem>> by=items.findByGradebookId(id).stream().collect(Collectors.groupingBy(GradeItem::getStudentId));Map<String,AssessmentComponent> componentById=cs.stream().collect(Collectors.toMap(AssessmentComponent::getId,x->x));AssessmentScheme scheme=schemes.findById(g.getSchemeId()).orElseThrow();int version=g.getSubmissionNo();String snapshot;try{snapshot=json.writeValueAsString(Map.of("snapshotVersion",1,"gradebookId",id,"students",ss));}catch(Exception e){throw new IllegalArgumentException("成绩快照序列化失败",e);}String hash=hash(snapshot);for(GradebookStudent student:ss){BigDecimal total=by.getOrDefault(student.getStudentId(),List.of()).stream().filter(x->x.getConvertedScore()!=null).map(x->{AssessmentComponent c=componentById.get(x.getComponentId());return c==null?BigDecimal.ZERO:x.getConvertedScore().divide(c.getMaxScore(),8,java.math.RoundingMode.HALF_UP).multiply(c.getWeight());}).reduce(BigDecimal.ZERO,BigDecimal::add);CourseGrade cg=new CourseGrade();cg.setGradebookId(id);cg.setStudentId(student.getStudentId());cg.setTotalScore(total);cg.setPassed(total.compareTo(scheme.getPassScore())>=0);cg.setVersionNo(version);cg.setSnapshotHash(hash);courseGrades.save(cg);notifications.published(id,student.getStudentId(),g.getOfferingId(),String.valueOf(version));}GradePublishSnapshot p=new GradePublishSnapshot();p.setGradebookId(id);p.setVersionNo(version);p.setSnapshotJson(snapshot);p.setSnapshotHash(hash);p.setPublishedBy(actor);p.setPublishedAt(LocalDateTime.now());snapshots.save(p);g.setStatus("PUBLISHED");g.setPublishedAt(LocalDateTime.now());audit.log(actor,"EDU_GRADEBOOK_PUBLISH","gradebookId="+id+",version="+version);return gradebooks.save(g);}
 @Transactional(readOnly=true) public List<CourseGrade> studentGrades(String studentId){return courseGrades.findByStudentIdOrderByVersionNoDesc(studentId).stream().filter(g->gradebooks.findById(g.getGradebookId()).map(x->"PUBLISHED".equals(x.getStatus())).orElse(false)).toList();}
 @Transactional(readOnly=true) public CourseGrade studentGrade(String id,String studentId){return studentGrades(studentId).stream().filter(g->g.getId().equals(id)).findFirst().orElseThrow(()->new org.springframework.security.access.AccessDeniedException("成绩不存在或尚未发布"));}
 private CourseOffering authorizedOffering(String id,String actor){CourseOffering offering=offerings.findById(id).orElseThrow(()->new IllegalArgumentException("课程开设不存在"));if(!dataScopes.resolve(actor).teacherIds().contains(offering.getTeacherId()))throw new AccessDeniedException("无权访问该课程开设");return offering;}
 private Gradebook authorizedGradebook(String id,String actor){Gradebook gradebook=gradebooks.findById(id).orElseThrow(()->new IllegalArgumentException("成绩册不存在"));if(!dataScopes.resolve(actor).teacherIds().contains(gradebook.getTeacherId()))throw new AccessDeniedException("无权访问该成绩册");return gradebook;}
 private String serverSchoolId(String actor){return dataScopes.resolve(actor).campusIds().stream().findFirst().orElse("DEFAULT");}
 private void validateScheme(SchemeCommand c){if(c==null||c.components()==null||c.components().isEmpty())throw new IllegalArgumentException("至少配置一个成绩项目");if(c.totalScore()==null||c.totalScore().signum()<=0||c.passScore()==null||c.passScore().signum()<0||c.passScore().compareTo(c.totalScore())>0)throw new IllegalArgumentException("分数范围无效");for(ComponentCommand x:c.components())if(!"MANUAL".equals(x.sourceType()))throw new IllegalArgumentException("第一片只支持 MANUAL 成绩项目");validateWeights(c.components().stream().map(x->{AssessmentComponent a=new AssessmentComponent();a.setWeight(x.weight());return a;}).toList());}
 private void validateWeights(List<AssessmentComponent> list){BigDecimal total=list.stream().map(AssessmentComponent::getWeight).reduce(BigDecimal.ZERO,BigDecimal::add);if(total.compareTo(new BigDecimal("100"))!=0)throw new IllegalArgumentException("成绩项目权重合计必须为100");}
 private Map<String,Object> snapshotStudent(GradebookStudent s){return Map.of("studentId",s.getStudentId(),"studentNo",s.getStudentNo(),"studentName",s.getStudentName(),"administrativeClassId",s.getAdministrativeClassId()==null?"":s.getAdministrativeClassId(),"enrollmentStatus",s.getEnrollmentStatus(),"sourceMemberId",s.getSourceMemberId());}
 private String hash(Object value){try{String text=value instanceof String?(String)value:json.writeValueAsString(value);byte[] b=MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8));StringBuilder out=new StringBuilder();for(byte x:b)out.append(String.format("%02x",x));return out.toString();}catch(Exception e){throw new IllegalStateException("快照哈希失败",e);}}
}
