<template>
  <section class="lesson-page">
    <header class="page-head"><div><h1>教案</h1><p>从教学计划章节或已发布课次创建，实训条件按教案类型动态展示。</p></div><el-button type="primary" @click="openCreate">新建教案</el-button></header>
    <el-form inline @submit.prevent="load"><el-form-item label="教学班"><el-select v-model="filters.offeringId" clearable filterable style="width:320px"><el-option v-for="item in offerings" :key="item.id" :value="item.id" :label="offeringLabel(item)" /></el-select></el-form-item><el-form-item label="周次"><el-input-number v-model="filters.teachingWeek" :min="1" :max="60" /></el-form-item><el-button @click="load">查询</el-button></el-form>
    <el-table v-loading="loading" :data="rows" stripe border><el-table-column prop="title" label="标题" min-width="220" /><el-table-column label="教学班" min-width="240"><template #default="{row}">{{ offeringLabel(findOffering(row.offeringId)) }}</template></el-table-column><el-table-column prop="teachingWeek" label="周次" width="80" /><el-table-column prop="lessonHours" label="课时" width="80" /><el-table-column prop="status" label="状态" width="110" /><el-table-column prop="currentVersionNo" label="版本" width="80" /><el-table-column label="操作" width="230" fixed="right"><template #default="{row}"><el-button link type="primary" @click="openWorkspace(row)">工作台</el-button><el-button link @click="editLesson(row)">编辑</el-button><el-button link type="danger" @click="archive(row)">归档</el-button></template></el-table-column></el-table>
    <el-pagination v-model:current-page="page" v-model:page-size="size" :total="total" layout="total, sizes, prev, pager, next" @change="load" />

    <el-drawer v-model="workspace" title="教案工作台" size="78%"><template v-if="selected"><el-descriptions :column="3" border><el-descriptions-item label="标题">{{ selected.title }}</el-descriptions-item><el-descriptions-item label="教学班">{{ offeringLabel(findOffering(selected.offeringId)) }}</el-descriptions-item><el-descriptions-item label="状态"><el-tag>{{ selected.status }}</el-tag></el-descriptions-item><el-descriptions-item label="版本">v{{ selected.currentVersionNo || 1 }}</el-descriptions-item><el-descriptions-item label="教学周">{{ selected.teachingWeek || '—' }}</el-descriptions-item><el-descriptions-item label="审核">{{ reviewText }}</el-descriptions-item></el-descriptions><el-tabs v-model="tab" class="tabs"><el-tab-pane label="内容预览" name="content"><div class="preview"><h2>{{ selected.title }}</h2><p><b>教学目标</b><br>{{ selected.objectives }}</p><p><b>重点</b><br>{{ selected.keyPoints || '—' }}</p><p><b>难点</b><br>{{ selected.difficultPoints || '—' }}</p><p><b>教学方法</b><br>{{ selected.teachingMethod || '—' }}</p><p><b>课堂活动</b><br>{{ selected.classroomActivity || '—' }}</p></div></el-tab-pane><el-tab-pane label="版本" name="versions"><el-table :data="versions" border><el-table-column prop="versionNo" label="版本" width="90" /><el-table-column prop="status" label="状态" width="110" /><el-table-column prop="createTime" label="生成时间" /><el-table-column prop="submittedAt" label="提交时间" /></el-table></el-tab-pane><el-tab-pane label="审核" name="review"><el-empty v-if="!reviewStatus" description="暂无审核记录" /><el-descriptions v-else border><el-descriptions-item label="状态">{{ reviewStatus.status }}</el-descriptions-item><el-descriptions-item label="意见">{{ reviewStatus.comment || '—' }}</el-descriptions-item></el-descriptions></el-tab-pane></el-tabs><div class="drawer-actions"><el-button @click="workspace=false">关闭</el-button><el-button type="primary" :disabled="selected.status !== 'DRAFT'" @click="submitLesson">提交审核</el-button></div></template></el-drawer>

    <el-dialog v-model="editor" :title="editing ? '编辑教案' : '新建教案'" width="760px" destroy-on-close><el-form :model="form" label-width="125px" class="lesson-form"><el-form-item label="教学班" required><el-select v-model="form.offeringId" filterable style="width:100%" @change="loadPlanRefs"><el-option v-for="item in offerings" :key="item.id" :value="item.id" :label="offeringLabel(item)" /></el-select></el-form-item><el-form-item label="来源章节"><el-select v-model="form.planItemId" clearable filterable style="width:100%" placeholder="可选：选择计划章节"><el-option v-for="item in planItems" :key="item.id" :value="item.id" :label="`${item.chapterNo || ''} · ${item.chapterName}`" /></el-select></el-form-item><el-form-item label="已发布课次"><el-select v-model="form.scheduleEntryId" clearable filterable style="width:100%" placeholder="可选：选择已发布课次"><el-option v-for="item in scheduleEntries" :key="item.id" :value="item.id" :label="scheduleLabel(item)" /></el-select></el-form-item><el-form-item label="标题" required><el-input v-model="form.title" maxlength="200" /></el-form-item><el-form-item label="教学周"><el-input-number v-model="form.teachingWeek" :min="1" :max="60" /></el-form-item><el-form-item label="课时" required><el-input-number v-model="form.lessonHours" :min="1" /></el-form-item><el-form-item label="教案类型" required><el-select v-model="form.lessonType" style="width:100%" placeholder="从字典选择"><el-option v-for="o in lessonTypes" :key="o.value" :label="o.label" :value="o.value" /></el-select></el-form-item><el-form-item label="教学目标" required><el-input v-model="form.objectives" type="textarea" :rows="3" /></el-form-item><el-form-item label="重点"><el-input v-model="form.keyPoints" type="textarea" :rows="2" /></el-form-item><el-form-item label="难点"><el-input v-model="form.difficultPoints" type="textarea" :rows="2" /></el-form-item><el-form-item label="教学方法"><el-input v-model="form.teachingMethod" type="textarea" :rows="2" /></el-form-item><el-form-item label="课堂活动"><el-input v-model="form.classroomActivity" type="textarea" :rows="3" /></el-form-item><el-form-item label="考核设计"><el-input v-model="form.assessmentDesign" type="textarea" :rows="2" /></el-form-item><template v-if="isPractical"><el-divider content-position="left">实训条件</el-divider><el-form-item label="安全注意事项" required><el-input v-model="form.safetyNotes" type="textarea" :rows="2" /></el-form-item><el-form-item label="设备要求" required><el-input v-model="form.equipmentRequirements" type="textarea" :rows="2" /></el-form-item></template><el-form-item label="课后反思"><el-input v-model="form.afterClassReflection" type="textarea" :rows="2" /></el-form-item></el-form><template #footer><el-button @click="editor=false">取消</el-button><el-button type="primary" @click="saveLesson">保存草稿</el-button></template></el-dialog>
  </section>
</template>
<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { dictionaryOptions } from '../../../api/admin'
import { archiveTeachingDomainApi, createTeachingDomainApi, publishedScheduleEntries, teachingCenterOfferings, teachingDomainChildrenApi, teachingDomainDetailApi, teachingDomainPageApi, transitionTeachingDomainApi, updateTeachingDomainApi } from '../api/teachingCenter'
const offerings=ref([]);const rows=ref([]);const total=ref(0);const page=ref(1);const size=ref(20);const loading=ref(false);const filters=reactive({offeringId:'',teachingWeek:''});const lessonTypes=ref([]);const planItems=ref([]);const scheduleEntries=ref([])
const editor=ref(false);const editing=ref('');const workspace=ref(false);const selected=ref(null);const versions=ref([]);const reviewStatus=ref(null);const tab=ref('content')
const form=reactive({offeringId:'',teachingPlanId:'',planItemId:'',scheduleEntryId:'',title:'',lessonNo:'',teachingWeek:'',lessonHours:1,lessonType:'',objectives:'',keyPoints:'',difficultPoints:'',teachingMethod:'',classroomActivity:'',assessmentDesign:'',safetyNotes:'',equipmentRequirements:'',afterClassReflection:''})
const offeringLabel=x=>x?`${x.semesterCode||x.semesterName||'当前学期'} · ${x.courseName||x.courseId||''} · ${x.teachingClassName||x.name||''}`:'—';const findOffering=id=>offerings.value.find(x=>x.id===id);const scheduleLabel=x=>x?`${x.weekName||`第${x.week||''}周`} · ${x.courseName||''} · ${x.classroomName||x.roomName||'未标注教室'}`:'—'
const isPractical=computed(()=>lessonTypes.value.find(x=>x.value===form.lessonType)?.label?.includes('实训'))
const load=async()=>{loading.value=true;try{const r=await teachingDomainPageApi('lesson-plans',{...filters,page:page.value-1,size:size.value});rows.value=r.data?.content||[];total.value=r.data?.totalElements||0}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
const resetForm=()=>Object.assign(form,{offeringId:filters.offeringId,teachingPlanId:'',planItemId:'',scheduleEntryId:'',title:'',lessonNo:'',teachingWeek:'',lessonHours:1,lessonType:lessonTypes.value[0]?.value||'',objectives:'',keyPoints:'',difficultPoints:'',teachingMethod:'',classroomActivity:'',assessmentDesign:'',safetyNotes:'',equipmentRequirements:'',afterClassReflection:''})
const openCreate=()=>{editing.value='';resetForm();editor.value=true;loadPlanRefs()}
const editLesson=row=>{editing.value=row.id;Object.assign(form,form,row);editor.value=true;loadPlanRefs()}
const loadPlanRefs=async()=>{if(!form.offeringId)return;try{const plans=await teachingDomainPageApi('plans',{offeringId:form.offeringId,page:0,size:100});const first=plans.data?.content?.[0];planItems.value=first?(await teachingDomainChildrenApi('plans',first.id,'items',{page:0,size:100})).data?.content||[]:[];const schedules=await publishedScheduleEntries(form.offeringId);scheduleEntries.value=schedules.data?.content||schedules.data||[]}catch(e){planItems.value=[];scheduleEntries.value=[]}}
const saveLesson=async()=>{if(!form.offeringId||!form.title||!form.lessonHours||!form.objectives||!form.lessonType)return ElMessage.warning('请完成教学班、标题、课时、类型和教学目标');if(isPractical.value&&(!form.safetyNotes||!form.equipmentRequirements))return ElMessage.warning('实训教案必须填写安全注意事项和设备要求');try{const {offeringId,scheduleEntryId,title,...attributes}=form;const payload={offeringId,scheduleEntryId,title,attributes};editing.value?await updateTeachingDomainApi('lesson-plans',editing.value,payload):await createTeachingDomainApi('lesson-plans',payload);editor.value=false;ElMessage.success('草稿已保存');await load()}catch(e){ElMessage.error(e.message)}}
const openWorkspace=async row=>{try{const r=await teachingDomainDetailApi('lesson-plans',row.id);selected.value=r.data||row;versions.value=(await teachingDomainChildrenApi('lesson-plans',row.id,'versions',{page:0,size:100})).data?.content||[];workspace.value=true}catch(e){ElMessage.error(e.message)}}
const submitLesson=async()=>{try{await transitionTeachingDomainApi('lesson-plans',selected.value.id,'SUBMITTED');ElMessage.success('已提交审核');workspace.value=false;await load()}catch(e){ElMessage.error(e.message)}}
const reviewText=computed(()=>reviewStatus.value?.status||'待提交')
const archive=async row=>{await ElMessageBox.confirm('归档后将从默认列表隐藏，是否继续？','确认');try{await archiveTeachingDomainApi('lesson-plans',row.id);ElMessage.success('已归档');await load()}catch(e){ElMessage.error(e.message)}}
onMounted(async()=>{try{const [o,d]=await Promise.all([teachingCenterOfferings(),dictionaryOptions('EDU_LESSON_TYPE')]);offerings.value=o.data||[];lessonTypes.value=(d.data||[]).map(x=>({label:x.dictName||x.itemName||x.name||x.label,value:x.dictValue||x.itemValue||x.value||x.code}));await load()}catch(e){ElMessage.error(e.message)}})
</script>
<style scoped>.lesson-page{padding:24px}.page-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.page-head h1{margin:0 0 6px}.page-head p{margin:0;color:#7b8794}.el-pagination{margin-top:20px;justify-content:flex-end}.tabs{margin-top:22px}.preview{padding:24px;line-height:1.8;background:#f8fafc;border-radius:8px}.preview h2{margin-top:0}.drawer-actions{display:flex;justify-content:flex-end;border-top:1px solid #ebeef5;padding-top:16px;margin-top:20px}.lesson-form{padding:12px 10px}.lesson-form .el-divider{margin:8px 0 18px}</style>
