<template>
  <section class="workbench">
    <header class="head"><div><h1>集体备课</h1><p>围绕主题协作备课，沉淀讨论、资料、结论和教案关联</p></div><el-button type="primary" @click="openCreate">新建备课</el-button></header>
    <el-form inline @submit.prevent="load"><el-form-item label="教学班"><el-select v-model="filters.offeringId" clearable filterable style="width:280px"><el-option v-for="item in offerings" :key="item.id" :value="item.id" :label="offeringLabel(item)" /></el-select></el-form-item><el-button @click="load">查询</el-button></el-form>
    <el-table v-loading="loading" :data="rows" stripe border><el-table-column prop="title" label="主题" min-width="220" /><el-table-column label="类型" width="110"><template #default="{ row }">{{ labelOf(types, row.preparationType) }}</template></el-table-column><el-table-column prop="scheduledAt" label="时间" width="180" /><el-table-column prop="ownerTeacherName" label="主持人" width="130" /><el-table-column prop="conclusion" label="结论" min-width="220" show-overflow-tooltip /><el-table-column label="操作" width="230" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="edit(row)">编辑</el-button><el-button link @click="openDiscussion(row)">讨论/资料</el-button><el-button link type="success" :disabled="row.status !== 'DRAFT'" @click="submit(row)">提交审核</el-button></template></el-table-column></el-table>
    <el-pagination v-model:current-page="page" v-model:page-size="size" :total="total" layout="total, prev, pager, next" @change="load" />
    <el-dialog v-model="dialog" :title="editing ? '编辑备课' : '新建备课'" width="760px">
      <el-form ref="formRef" :model="form" :rules="rules" label-width="105px">
        <el-form-item label="教学班" prop="offeringId"><el-select v-model="form.offeringId" filterable style="width:100%"><el-option v-for="item in offerings" :key="item.id" :value="item.id" :label="offeringLabel(item)" /></el-select></el-form-item>
        <el-form-item label="主题" prop="title"><el-input v-model="form.title" maxlength="200" /></el-form-item>
        <el-form-item label="备课类型" prop="preparationType"><el-select v-model="form.preparationType" style="width:100%"><el-option v-for="item in types" :key="item.value" :value="item.value" :label="item.label" /></el-select></el-form-item>
        <el-form-item label="时间" prop="scheduledAt"><el-date-picker v-model="form.scheduledAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" style="width:100%" /></el-form-item>
        <el-form-item label="主持人" prop="ownerTeacherId"><el-select v-model="form.ownerTeacherId" filterable style="width:100%"><el-option v-for="item in teachers" :key="item.id" :value="item.id" :label="personLabel(item)" /></el-select></el-form-item>
        <el-form-item label="课表项"><el-select v-model="form.scheduleEntryId" clearable filterable placeholder="选择已发布课次（只读）" style="width:100%" @focus="loadSchedule"><el-option v-for="item in schedules" :key="item.id" :value="item.id" :label="scheduleLabel(item)" /></el-select></el-form-item>
        <el-form-item label="议程"><el-input v-model="form.agenda" type="textarea" :rows="3" /></el-form-item><el-form-item label="关联教案"><el-select v-model="form.outcomeLessonPlanId" clearable filterable style="width:100%"><el-option v-for="item in lessons" :key="item.id" :value="item.id" :label="item.title" /></el-select></el-form-item>
        <el-form-item v-if="isCollective" label="邀请成员"><el-select v-model="form.memberIds" multiple filterable style="width:100%"><el-option v-for="item in teachers" :key="item.id" :value="item.id" :label="personLabel(item)" /></el-select></el-form-item>
        <el-form-item label="讨论"><el-input v-model="form.discussion" type="textarea" :rows="3" /></el-form-item><el-form-item label="结论"><el-input v-model="form.conclusion" type="textarea" :rows="3" /></el-form-item>
      </el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存草稿</el-button></template>
    </el-dialog>
    <el-dialog v-model="discussionDialog" title="备课讨论与资料" width="700px"><el-form label-width="80px"><el-form-item label="讨论"><el-input v-model="discussion.content" type="textarea" :rows="4" /></el-form-item><el-form-item label="资料"><el-upload :show-file-list="false" :before-upload="uploadMaterial"><el-button>上传资料</el-button></el-upload><span class="file-name">{{ discussion.fileName }}</span></el-form-item></el-form><template #footer><el-button @click="discussionDialog=false">关闭</el-button><el-button type="primary" @click="saveDiscussion">保存</el-button></template></el-dialog>
  </section>
</template>
<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { dictionaryOptions, employees } from '../../iam/api'
import { createPreparation, createPreparationChild, preparationPage, publishedScheduleEntries, submitPreparation, teachingCenterOfferings, teachingDomainPageApi, updatePreparation } from '../api/teachingCenter'
const offerings=ref([]), teachers=ref([]), lessons=ref([]), schedules=ref([]), types=ref([]), rows=ref([]), total=ref(0), page=ref(1), size=ref(20), loading=ref(false), dialog=ref(false), editing=ref(''), formRef=ref()
const filters=reactive({offeringId:''}); const form=reactive({offeringId:'',title:'',preparationType:'',scheduledAt:'',ownerTeacherId:'',scheduleEntryId:'',agenda:'',outcomeLessonPlanId:'',memberIds:[],discussion:'',conclusion:''}); const discussionDialog=ref(false); const discussion=reactive({preparationId:'',content:'',fileName:''})
const rules={offeringId:[{required:true,message:'请选择教学班'}],title:[{required:true,message:'请输入主题'}],preparationType:[{required:true,message:'请选择类型'}],scheduledAt:[{required:true,message:'请选择时间'}],ownerTeacherId:[{required:true,message:'请选择主持人'}]}
const isCollective=computed(()=>types.value.find(item=>item.value===form.preparationType)?.label?.includes('集体')); const unwrap=r=>r?.data?.content||r?.data||[]; const labelOf=(a,v)=>a.find(x=>x.value===v)?.label||v||'-'; const offeringLabel=i=>`${i.semesterCode||''} · ${i.courseName||''} · ${i.teachingClassName||''}`; const personLabel=i=>i.name||i.employeeName||i.realName||i.id; const scheduleLabel=i=>`${i.startTime||i.date||''} · ${i.courseName||i.location||''}`
const load=async()=>{loading.value=true;try{const r=await preparationPage({...filters,page:page.value-1,size:size.value});rows.value=unwrap(r);total.value=r?.data?.totalElements||rows.value.length}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
const loadSchedule=async()=>{if(!form.offeringId||schedules.value.length)return;try{schedules.value=unwrap(await publishedScheduleEntries(form.offeringId))}catch(e){ElMessage.error(e.message)}}
const openCreate=()=>{editing.value='';Object.assign(form,{offeringId:filters.offeringId,title:'',preparationType:types.value[0]?.value||'',scheduledAt:'',ownerTeacherId:'',scheduleEntryId:'',agenda:'',outcomeLessonPlanId:'',memberIds:[],discussion:'',conclusion:''});schedules.value=[];dialog.value=true}
const edit=row=>{editing.value=row.id;Object.assign(form,row,{memberIds:row.memberIds||[]});dialog.value=true}
const save=async()=>{try{await formRef.value.validate();const body={...form};delete body.memberIds;delete body.discussion;if(editing.value)await updatePreparation(editing.value,body);else{const r=await createPreparation(body);for(const teacherId of form.memberIds)await createPreparationChild(r?.data?.id,'members',{teacherId})}dialog.value=false;ElMessage.success('草稿已保存');await load()}catch(e){if(e?.message)ElMessage.error(e.message)}}
const submit=async row=>{try{await submitPreparation(row.id);ElMessage.success('已提交审核');await load()}catch(e){ElMessage.error(e.message)}}
const openDiscussion=row=>{Object.assign(discussion,{preparationId:row.id,content:row.discussion||'',fileName:''});discussionDialog.value=true}
const uploadMaterial=async file=>{try{await createPreparationChild(discussion.preparationId,'materials',{fileName:file.name});discussion.fileName=file.name;ElMessage.success('资料已上传')}catch(e){ElMessage.error(e.message)}return false}
const saveDiscussion=async()=>{try{await createPreparationChild(discussion.preparationId,'comments',{content:discussion.content});discussionDialog.value=false;ElMessage.success('已保存')}catch(e){ElMessage.error(e.message)}}
watch(()=>form.offeringId,async id=>{if(id)try{lessons.value=unwrap(await teachingDomainPageApi('lesson-plans',{offeringId:id,page:0,size:100}))}catch(e){ElMessage.error(e.message)}})
onMounted(async()=>{try{const[o,t,d]=await Promise.all([teachingCenterOfferings(),employees({page:0,size:100}),dictionaryOptions('EDU_PREPARATION_TYPE')]);offerings.value=unwrap(o);teachers.value=unwrap(t);types.value=(d?.data||[]).map(i=>({value:i.dictValue,label:i.dictName}));await load()}catch(e){ElMessage.error(e.message)}})
</script>
<style scoped>.workbench{padding:24px}.head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:18px}.head h1{margin:0 0 6px}.head p{margin:0;color:#7b8794}.el-pagination{margin-top:18px;justify-content:flex-end}.file-name{margin-left:12px;color:#667085}</style>
