<template>
  <section class="workbench">
    <header class="head"><div><h1>错题沉淀</h1><p>学生查看本人错题；教师仅查看已授权教学班的聚合统计</p></div><el-button type="primary" @click="openCreate">人工录入</el-button></header>
    <el-alert v-if="loadError" type="error" :closable="false" show-icon :title="loadError" />
    <el-tabs v-model="scope" @tab-change="load"><el-tab-pane name="student" label="我的错题" /><el-tab-pane name="teacher" label="教师聚合" /></el-tabs>
    <el-form inline @submit.prevent="load"><el-form-item label="知识点"><el-select v-model="filters.knowledgePointId" clearable filterable style="width:220px"><el-option v-for="x in knowledgePoints" :key="x.id" :value="x.id" :label="x.name" /></el-select></el-form-item><el-form-item label="掌握状态"><el-select v-model="filters.masteryStatus" clearable style="width:180px"><el-option v-for="x in masteryStatuses" :key="x.value" v-bind="x" /></el-select></el-form-item><el-button @click="load">查询</el-button></el-form>
    <el-table v-loading="loading" :data="rows" stripe border><el-table-column prop="questionName" label="题目" min-width="220" /><el-table-column prop="sourceType" label="来源" width="130"><template #default="{row}">{{ labelOf(sourceTypes,row.sourceType) }}</template></el-table-column><el-table-column v-if="scope==='student'" prop="wrongCount" label="错误次数" width="100" /><el-table-column v-if="scope==='teacher'" prop="studentCount" label="学生数" width="100" /><el-table-column prop="knowledgePointName" label="知识点" min-width="160" /><el-table-column prop="lastWrongAt" label="最近错误" width="180" /><el-table-column label="掌握状态" width="130"><template #default="{row}">{{ labelOf(masteryStatuses,row.masteryStatus) }}</template></el-table-column><el-table-column label="操作" width="190" fixed="right"><template #default="{row}"><el-button v-if="scope==='student'" link type="primary" @click="markMastery(row)">标记掌握</el-button><el-button link @click="jumpSource(row)" :disabled="!row.sourceRef">查看来源</el-button></template></el-table-column></el-table>
    <el-empty v-if="!loading&&!rows.length" description="暂无错题沉淀" /><el-pagination v-model:current-page="page" v-model:page-size="size" :total="total" layout="total, prev, pager, next" @change="load" />
    <el-dialog v-model="dialog" title="人工录入错题" width="620px"><el-form ref="formRef" :model="form" :rules="rules" label-width="100px"><el-form-item label="题目" prop="questionId"><el-select v-model="form.questionId" filterable style="width:100%" @focus="loadQuestions"><el-option v-for="x in questions" :key="x.id" :value="x.id" :label="x.name||x.stem" /></el-select></el-form-item><el-form-item label="知识点" prop="knowledgePointId"><el-select v-model="form.knowledgePointId" filterable style="width:100%"><el-option v-for="x in knowledgePoints" :key="x.id" :value="x.id" :label="x.name" /></el-select></el-form-item><el-form-item label="错误原因"><el-select v-model="form.errorReason" clearable style="width:100%"><el-option v-for="x in errorReasons" :key="x.value" v-bind="x" /></el-select></el-form-item><el-form-item label="错题说明"><el-input v-model="form.studentNote" type="textarea" /></el-form-item><el-form-item label="来源"><el-tag type="warning">MANUAL · 人工录入</el-tag></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :disabled="!!loadError" @click="save">保存</el-button></template></el-dialog>
  </section>
</template>
<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { dictionaryOptions } from '../../iam/api'
import { createMistake, mistakesPage, questions as questionPage, transitionMistake } from '../api/teachingCenter'
import { knowledgePointTree } from '../api/teachingCenter'
const scope=ref('student'),rows=ref([]),questions=ref([]),knowledgePoints=ref([]),loading=ref(false),loadError=ref(''),page=ref(1),size=ref(20),total=ref(0),dialog=ref(false),formRef=ref()
const sourceTypes=ref([]),masteryStatuses=ref([]),errorReasons=ref([]);const filters=reactive({knowledgePointId:'',masteryStatus:''});const form=reactive({questionId:'',knowledgePointId:'',errorReason:'',studentNote:''});const rules={questionId:[{required:true,message:'请选择题目'}],knowledgePointId:[{required:true,message:'请选择知识点'}]};const unwrap=r=>r?.data?.content||r?.data||[];const labelOf=(a,v)=>a.find(x=>x.value===v)?.label||v||'-'
const load=async()=>{loading.value=true;try{const r=await mistakesPage({...filters,scope:scope.value,page:page.value-1,size:size.value});rows.value=unwrap(r);total.value=r?.data?.totalElements||rows.value.length}catch(e){loadError.value=e.message||'加载失败'}finally{loading.value=false}}
const loadQuestions=async()=>{if(questions.value.length)return;try{questions.value=unwrap(await questionPage({page:0,size:100}))}catch(e){ElMessage.error(e.message)}}
const openCreate=()=>{Object.assign(form,{questionId:'',knowledgePointId:'',errorReason:'',studentNote:''});dialog.value=true};const save=async()=>{try{await formRef.value.validate();const manual=sourceTypes.value.find(x=>x.value==='MANUAL');if(!manual)throw new Error('错题来源字典未配置 MANUAL，暂不能人工录入');await createMistake({...form,sourceType:manual.value});dialog.value=false;ElMessage.success('已保存，来源已明确标记为人工录入');await load()}catch(e){ElMessage.error(e.message||'保存失败')}}
const markMastery=async row=>{try{const target=masteryStatuses.value.find(x=>/掌握|master/i.test(x.label));if(!target)throw new Error('掌握状态字典未配置');await transitionMistake(row.id,target.value);ElMessage.success('已更新掌握状态');await load()}catch(e){ElMessage.error(e.message)}}
const jumpSource=row=>{if(row.sourceUrl)window.open(row.sourceUrl,'_blank');else ElMessage.info('来源由业务中心提供，当前暂无跳转地址')}
onMounted(async()=>{try{const [s,m,e,k]=await Promise.all([dictionaryOptions('EDU_ERROR_SOURCE_TYPE'),dictionaryOptions('EDU_ERROR_MASTERY_STATUS'),dictionaryOptions('EDU_ERROR_REASON'),knowledgePointTree()]);sourceTypes.value=(s?.data||[]).map(x=>({value:x.dictValue,label:x.dictName}));masteryStatuses.value=(m?.data||[]).map(x=>({value:x.dictValue,label:x.dictName}));errorReasons.value=(e?.data||[]).map(x=>({value:x.dictValue,label:x.dictName}));knowledgePoints.value=unwrap(k).flatMap(x=>[x,...(x.children||[])]);await load()}catch(e){loadError.value=e.message||'字典加载失败，请检查配置'}})
</script>
<style scoped>.workbench{padding:24px}.head{display:flex;justify-content:space-between;margin-bottom:18px}.head h1{margin:0 0 6px}.head p{margin:0;color:#7b8794}.el-pagination{margin-top:18px;justify-content:flex-end}.el-alert{margin-bottom:16px}</style>
