<template>
  <section class="workbench"><header class="head"><div><h1>课件与教学材料</h1><p>版本化管理教学文件，上传后可预览、设为当前版本并提交审核</p></div><el-button type="primary" @click="openCreate">新建资源</el-button></header>
    <el-tabs v-if="showTabs" v-model="domain" @tab-change="load"><el-tab-pane name="coursewares" label="课件" /><el-tab-pane name="materials" label="教学材料" /></el-tabs>
    <el-form inline @submit.prevent="load"><el-form-item label="分类"><el-select v-model="filters.category" clearable style="width:180px"><el-option v-for="x in categories" :key="x.value" :value="x.value" :label="x.label" /></el-select></el-form-item><el-form-item label="共享范围"><el-select v-model="filters.shareScope" clearable style="width:180px"><el-option v-for="x in scopes" :key="x.value" :value="x.value" :label="x.label" /></el-select></el-form-item><el-button @click="load">查询</el-button></el-form>
    <el-table v-loading="loading" :data="rows" stripe border><el-table-column prop="title" label="名称" min-width="220" /><el-table-column label="分类" width="130"><template #default="{row}">{{ labelOf(categories,row.resourceCategory||row.category) }}</template></el-table-column><el-table-column label="共享范围" width="130"><template #default="{row}">{{ labelOf(scopes,row.shareScope) }}</template></el-table-column><el-table-column prop="publishedVersionNo" label="当前版本" width="100" /><el-table-column label="操作" width="360" fixed="right"><template #default="{row}"><el-button link @click="versions(row)">版本</el-button><el-button link @click="edit(row)">编辑</el-button><el-button link @click="copy(row)">复制</el-button><el-button link type="success" :disabled="!row.id" @click="submit(row)">提交审核</el-button></template></el-table-column></el-table>
    <el-pagination v-model:current-page="page" v-model:page-size="size" :total="total" layout="total, prev, pager, next" @change="load" />
    <el-dialog v-model="dialog" :title="editing ? '编辑资源' : '新建资源'" width="650px"><el-form ref="formRef" :model="form" :rules="rules" label-width="100px"><el-form-item label="教学任务" prop="offeringId"><el-select v-model="form.offeringId" filterable style="width:100%"><el-option v-for="x in offerings" :key="x.id" :value="x.id" :label="offeringLabel(x)" /></el-select></el-form-item><el-form-item label="名称" prop="title"><el-input v-model="form.title" /></el-form-item><el-form-item label="分类" prop="resourceCategory"><el-select v-model="form.resourceCategory" style="width:100%"><el-option v-for="x in categories" :key="x.value" :value="x.value" :label="x.label" /></el-select></el-form-item><el-form-item label="来源"><el-select v-model="form.sourceType" clearable style="width:100%"><el-option value="UPLOAD" label="教师上传" /><el-option value="GENERATED" label="备课生成草稿" /><el-option value="COPIED" label="复制已有课件" /></el-select></el-form-item><el-form-item label="共享范围" prop="shareScope"><el-select v-model="form.shareScope" style="width:100%"><el-option v-for="x in scopes" :key="x.value" :value="x.value" :label="x.label" /></el-select></el-form-item><el-form-item label="说明"><el-input v-model="form.description" type="textarea" :rows="3" /></el-form-item><el-form-item label="文件"><el-upload :show-file-list="false" :before-upload="upload" :on-progress="progress"><el-button>选择文件并上传</el-button></el-upload><el-progress v-if="uploading" :percentage="uploadPercent" /><span>{{ fileName }}</span></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
    <el-dialog v-model="versionDialog" title="版本列表" width="820px"><el-table :data="versionRows"><el-table-column prop="versionNo" label="版本" width="80" /><el-table-column prop="fileName" label="文件" min-width="200" /><el-table-column prop="status" label="状态" width="110" /><el-table-column prop="fileSize" label="大小" width="100" /><el-table-column prop="uploadedAt" label="上传时间" width="180" /><el-table-column label="操作" width="320"><template #default="{row}"><el-button link @click="preview(row)">预览</el-button><el-button link type="success" :disabled="row.status!=='APPROVED'" @click="publish(row)">发布</el-button><el-button link type="primary" :disabled="row.status!=='PUBLISHED'" @click="current(row)">设为当前</el-button><el-button link type="danger" :disabled="row.status==='ARCHIVED'" @click="archive(row)">归档</el-button></template></el-table-column></el-table></el-dialog>
  </section>
</template>
<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { dictionaryOptions } from '../../iam/api'
import { uploadManagedFile, downloadManagedFile } from '../../../api/admin'
import { addResourceVersion, copyResource, createResource, resourcePage, resourceVersions, setCurrentResourceVersion, submitResource, teachingCenterOfferings, transitionResourceVersion, updateResource } from '../api/teachingCenter'
const props=defineProps({initialDomain:{type:String,default:'coursewares'},showTabs:{type:Boolean,default:false}});const showTabs=props.showTabs;const domain=ref(props.initialDomain);const rows=ref([]),versionRows=ref([]),total=ref(0),page=ref(1),size=ref(20),loading=ref(false),dialog=ref(false),versionDialog=ref(false),editing=ref(''),versionResource=ref(null),formRef=ref(),uploading=ref(false),uploadPercent=ref(0),fileName=ref('')
const categories=ref([]),sources=ref([]),scopes=ref([]),offerings=ref([]);const filters=reactive({category:'',shareScope:''});const form=reactive({offeringId:'',title:'',resourceCategory:'',sourceType:'UPLOAD',shareScope:'',description:'',fileRef:''});const pendingFile=ref(null);const rules={offeringId:[{required:true,message:'请选择教学任务'}],title:[{required:true,message:'请输入名称'}],resourceCategory:[{required:true,message:'请选择分类'}],shareScope:[{required:true,message:'请选择共享范围'}]};const unwrap=r=>r?.data?.content||r?.data||[];const labelOf=(a,v)=>a.find(x=>x.value===v)?.label||v||'-';const offeringLabel=x=>[x.semesterCode,x.courseName,x.teachingClassName].filter(Boolean).join(' · ')
const load=async()=>{loading.value=true;try{const r=await resourcePage(domain.value,{...filters,page:page.value-1,size:size.value});rows.value=unwrap(r);total.value=r?.data?.totalElements||rows.value.length}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
const openCreate=()=>{editing.value='';Object.assign(form,{offeringId:offerings.value[0]?.id||'',title:'',resourceCategory:categories.value[0]?.value||'',sourceType:'UPLOAD',shareScope:scopes.value[0]?.value||'',description:'',fileRef:''});fileName.value='';dialog.value=true}
const copy=async row=>{try{const target=offerings.value.find(x=>x.id===row.offeringId)||offerings.value[0];if(!target)throw new Error('没有可用教学任务');await copyResource(domain.value,row.id,{offeringId:target.id,title:`${row.title}（副本）`,shareScope:row.shareScope||'PRIVATE'});ElMessage.success('已复制为草稿');await load()}catch(e){ElMessage.error(e.message)}}
const edit=row=>{editing.value=row.id;Object.assign(form,row);dialog.value=true}
const save=async()=>{try{await formRef.value.validate();const body={...form};delete body.fileRef;body.materialType=form.resourceCategory;let resource;if(editing.value)resource=await updateResource(domain.value,editing.value,body);else resource=await createResource(domain.value,body);const resourceId=editing.value||resource?.data?.id;if(pendingFile.value&&resourceId){uploading.value=true;const uploaded=await uploadManagedFile(pendingFile.value,domain.value.toUpperCase(),resourceId);const fileId=uploaded?.data?.id;if(!fileId)throw new Error('文件上传未返回文件标识');await addResourceVersion(domain.value,resourceId,{fileId,metadataJson:JSON.stringify({sourceType:form.sourceType})})}dialog.value=false;pendingFile.value=null;ElMessage.success('已保存并生成版本');await load()}catch(e){ElMessage.error(e.message)}finally{uploading.value=false}}
const upload=file=>{pendingFile.value=file;fileName.value=file.name;uploadPercent.value=100;ElMessage.success('文件已选择，保存资源后完成绑定');return false}
const progress=(_,percent)=>{uploadPercent.value=percent}
const versions=async row=>{versionResource.value=row;try{versionRows.value=unwrap(await resourceVersions(domain.value,row.id));versionDialog.value=true}catch(e){ElMessage.error(e.message)}}
const current=async row=>{try{await setCurrentResourceVersion(domain.value,versionResource.value.id,row.id);ElMessage.success('已设为当前版本');await versions(versionResource.value);await load()}catch(e){ElMessage.error(e.message)}}
const archive=async row=>{try{await transitionResourceVersion(domain.value,row.id,'archive');ElMessage.success('版本已归档');await versions(versionResource.value);await load()}catch(e){ElMessage.error(e.message)}}
const publish=async row=>{try{await transitionResourceVersion(domain.value,row.id,'publish');ElMessage.success('版本已发布');await versions(versionResource.value);await load()}catch(e){ElMessage.error(e.message)}}
const preview=async row=>{if(!row.fileId){ElMessage.info('当前版本没有关联文件');return}try{const blob=await downloadManagedFile(row.fileId);const url=URL.createObjectURL(blob);window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){ElMessage.error(e.message)}}
const submit=async row=>{try{const versions=unwrap(await resourceVersions(domain.value,row.id));const draft=versions.find(v=>['DRAFT','REJECTED'].includes(v.status));if(!draft)throw new Error('没有可提交审核的草稿版本');await submitResource(domain.value,draft.id);ElMessage.success('已提交审核');await load()}catch(e){ElMessage.error(e.message)}}
onMounted(async()=>{try{const[d,c,s,x,o]=await Promise.all([dictionaryOptions('EDU_RESOURCE_CATEGORY'),dictionaryOptions('EDU_RESOURCE_SOURCE'),dictionaryOptions('EDU_RESOURCE_SHARE_SCOPE'),dictionaryOptions('EDU_MATERIAL_CATEGORY'),teachingCenterOfferings()]);categories.value=(d?.data||[]).map(i=>({value:i.dictValue,label:i.dictName}));sources.value=(c?.data||[]).map(i=>({value:i.dictValue,label:i.dictName}));scopes.value=(s?.data||[]).map(i=>({value:i.dictValue,label:i.dictName}));offerings.value=unwrap(o);if(!categories.value.length)categories.value=(x?.data||[]).map(i=>({value:i.dictValue,label:i.dictName}));await load()}catch(e){ElMessage.error(e.message)}})
</script>
<style scoped>.workbench{padding:24px}.head{display:flex;justify-content:space-between;margin-bottom:18px}.head h1{margin:0 0 6px}.head p{margin:0;color:#7b8794}.el-pagination{margin-top:18px;justify-content:flex-end}</style>
