import { http } from './http'

const qs = (params = {}) => {
  const cleaned = Object.fromEntries(
    Object.entries(params).filter(([, v]) => v !== undefined && v !== null && v !== '')
  )
  return new URLSearchParams(cleaned).toString()
}

export const adminLogin = (payload) => http.post('/auth/login', payload)
export const changeOwnPassword = (payload) => http.post('/auth/account/change-password', payload)

export const listUsers = (params) => http.get(`/admin/users/list?${qs(params)}`)
export const createUser = (payload) => http.post('/admin/users', payload)
export const updateUser = (payload) => http.put('/admin/users', payload)
export const deleteUser = (id) => http.delete(`/admin/users/${id}`)
export const userByEmployee = (employeeId) => http.get(`/admin/users/by-employee/${employeeId}`)
export const unlockUser = (userId) => http.post(`/auth/account/unlock?${qs({ userId })}`)
export const forceLogoutUser = (userId) => http.post(`/auth/account/force-logout?${qs({ userId })}`)
export const resetUserPassword = (userId, newPassword) => http.post('/auth/account/reset-password', { userId, newPassword })

export const portalAdminApplications = () => http.get('/portal/admin/applications')
export const createPortalApplication = (payload) => http.post('/portal/admin/applications', payload)
export const updatePortalApplication = (id, payload) => http.put(`/portal/admin/applications/${id}`, payload)
export const deletePortalApplication = (id) => http.delete(`/portal/admin/applications/${id}`)
export const portalAdminWidgets = () => http.get('/portal/admin/widgets')
export const createPortalWidget = (payload) => http.post('/portal/admin/widgets', payload)
export const updatePortalWidget = (id, payload) => http.put(`/portal/admin/widgets/${id}`, payload)
export const deletePortalWidget = (id) => http.delete(`/portal/admin/widgets/${id}`)

export const listRoles = (params) => http.get(`/admin/roles/list?${qs(params)}`)
export const createRole = (payload) => http.post('/admin/roles/create', payload)
export const updateRole = (payload) => http.put('/admin/roles/update', payload)
export const roleDetail = (id) => http.get(`/admin/roles/${id}/detail`)
export const deleteRole = (id) => http.delete(`/admin/roles/delete/${id}`)

export const listMenus = (params) => http.get(`/admin/menus/list?${qs(params)}`)
export const menuTree = () => http.get('/admin/menus/tree')
export const currentAdminNavigation = () => http.get('/auth/navigation')
export const createMenu = (payload) => http.post('/admin/menus', payload)
export const updateMenu = (payload) => http.put('/admin/menus', payload)
export const deleteMenu = (id) => http.delete(`/admin/menus/${id}`)

export const permissions = (params) => http.get(`/admin/permissions/list?${qs(params)}`)
export const orgList = (params) => http.get(`/admin/organizations/list?${qs(params)}`)
export const orgDetail = (id) => http.get(`/admin/organizations/${id}`)
export const createOrg = (payload) => http.post('/admin/organizations', payload)
export const updateOrg = (payload) => http.put('/admin/organizations', payload)
export const deleteOrg = (id) => http.delete(`/admin/organizations/${id}`)
export const orgImpact = (id) => http.get(`/admin/organizations/${id}/impact`)

export const organizationUnits = (organizationId) => http.get(`/admin/iam/organization-units?${qs({ organizationId })}`)
export const saveOrganizationUnit = (payload) => payload.id
  ? http.put(`/admin/iam/organization-units/${payload.id}`, payload) : http.post('/admin/iam/organization-units', payload)
export const deleteOrganizationUnit = (id) => http.delete(`/admin/iam/organization-units/${id}`)
export const positions = () => http.get('/admin/iam/positions')
export const savePosition = (payload) => payload.id ? http.put(`/admin/iam/positions/${payload.id}`, payload) : http.post('/admin/iam/positions', payload)
export const deletePosition = (id) => http.delete(`/admin/iam/positions/${id}`)
export const jobTitles = () => http.get('/admin/iam/job-titles')
export const saveJobTitle = (payload) => payload.id ? http.put(`/admin/iam/job-titles/${payload.id}`, payload) : http.post('/admin/iam/job-titles', payload)
export const deleteJobTitle = (id) => http.delete(`/admin/iam/job-titles/${id}`)
export const jobLevels = () => http.get('/admin/iam/job-levels')
export const saveJobLevel = (payload) => payload.id ? http.put(`/admin/iam/job-levels/${payload.id}`, payload) : http.post('/admin/iam/job-levels', payload)
export const deleteJobLevel = (id) => http.delete(`/admin/iam/job-levels/${id}`)
export const employees = () => http.get('/admin/iam/employees')
export const saveEmployee = (payload) => payload.id ? http.put(`/admin/iam/employees/${payload.id}`, payload) : http.post('/admin/iam/employees', payload)
export const deleteEmployee = (id) => http.delete(`/admin/iam/employees/${id}`)
export const employeeAssignments = (employeeId) => http.get(`/admin/iam/assignments?${qs({ employeeId })}`)
export const saveEmployeeAssignment = (payload) => payload.id ? http.put(`/admin/iam/assignments/${payload.id}`, payload) : http.post('/admin/iam/assignments', payload)
export const deleteEmployeeAssignment = (id) => http.delete(`/admin/iam/assignments/${id}`)
export const downloadDirectoryImportTemplate = (type) => http.download(`/admin/iam/import/templates/${type}`)
export const importDirectoryData = (type, file, dryRun = false) => { const data = new FormData(); data.append('file', file); return http.upload(`/admin/iam/import/${type}?${qs({ dryRun })}`, data) }

export const dictTree = () => http.get('/admin/dicts/tree')
export const dictListByCode = (dictCode) => http.get(`/admin/dicts/list?${qs({ dictCode })}`)
export const createDict = (payload) => http.post('/admin/dicts', payload)
export const updateDict = (payload) => http.put('/admin/dicts', payload)
export const deleteDict = (id) => http.delete(`/admin/dicts/${id}`)

export const customerList = (params) => http.get(`/admin/customers/list?${qs(params)}`)
export const customerDetail = (id) => http.get(`/admin/customers/${id}`)
export const createCustomer = (payload) => http.post('/admin/customers', payload)
export const updateCustomer = (payload) => http.put('/admin/customers', payload)
export const deleteCustomer = (id) => http.delete(`/admin/customers/${id}`)

export const aiModels = (params) => http.get(`/ai-model/models/list?${qs(params)}`)
export const aiModelDetail = (id) => http.get(`/ai-model/models/${id}`)
export const createAiModel = (payload) => http.post('/ai-model/models', payload)
export const updateAiModel = (payload) => http.put('/ai-model/models', payload)
export const deleteAiModel = (id) => http.delete(`/ai-model/models/${id}`)

export const aiApis = (params) => http.get(`/ai-model/apis/list?${qs(params)}`)
export const aiApiDetail = (id) => http.get(`/ai-model/apis/${id}`)
export const createAiApi = (payload) => http.post('/ai-model/apis', payload)
export const updateAiApi = (payload) => http.put('/ai-model/apis', payload)
export const deleteAiApi = (id) => http.delete(`/ai-model/apis/${id}`)

export const aiAccounts = (params) => http.get(`/ai-model/accounts/list?${qs(params)}`)
export const createAiAccount = (payload) => http.post('/ai-model/accounts', payload)
export const updateAiAccount = (payload) => http.put('/ai-model/accounts', payload)
export const deleteAiAccount = (id) => http.delete(`/ai-model/accounts/${id}`)

export const apiParams = (params) => http.get(`/ai-model/api-params/list?${qs(params)}`)
export const createApiParam = (payload) => http.post('/ai-model/api-params', payload)
export const updateApiParam = (payload) => http.put('/ai-model/api-params', payload)
export const deleteApiParam = (id) => http.delete(`/ai-model/api-params/${id}`)

export const listWorkflows = (params) => http.get(`/admin/workflows/list?${qs(params)}`)
export const workflowDetail = (id) => http.get(`/admin/workflows/${id}`)
export const createWorkflow = (payload) => http.post('/admin/workflows', payload)
export const updateWorkflow = (payload) => http.put('/admin/workflows', payload)
export const deleteWorkflow = (id) => http.delete(`/admin/workflows/${id}`)
export const disableWorkflow = (id) => http.post(`/admin/workflows/${id}/disable`)
export const createWorkflowVersion = (id, version) => http.post(`/admin/workflows/${id}/versions`, { version })
export const listWorkflowExecutors = () => http.get('/admin/workflow-executors')
export const validateWorkflow = (id, ai = false) => http.post(`/admin/workflows/${id}/validate?ai=${ai}`)
export const publishWorkflow = (id) => http.post(`/admin/workflows/${id}/publish`)
export const getWorkflowAiSetting = () => http.get('/admin/workflow-ai/settings')
export const updateWorkflowAiSetting = (payload) => http.put('/admin/workflow-ai/settings', payload)
export const createWorkflowByAi = (requirement) => http.post('/admin/workflow-ai/draft', { requirement })

export const listWorkflowNodes = (params) => http.get(`/admin/workflow-nodes/list?${qs(params)}`)
export const createWorkflowNode = (payload) => http.post('/admin/workflow-nodes', payload)
export const getWorkflowByProject = (params) => http.get(`/admin/workflows/by-project?${qs(params)}`)
export const getWorkflowLocks = (params) => http.get(`/admin/workflows/locks?${qs(params)}`)
export const lockWorkflowNode = (payload) => http.post('/admin/workflows/lock', payload)
export const unlockWorkflowNode = (payload) => http.post('/admin/workflows/unlock', payload)
export const updateWorkflowNode = (payload) => http.put('/admin/workflow-nodes', payload)
export const deleteWorkflowNode = (id) => http.delete(`/admin/workflow-nodes/${id}`)

export const listForms = (params) => http.get(`/admin/forms/list?${qs(params)}`)
export const listFormFields = (formId) => http.get(`/admin/form-fields/list?${qs({ formId })}`)
export const createForm = (payload) => http.post('/admin/forms', payload)
export const updateForm = (payload) => http.put('/admin/forms', payload)
export const deleteForm = (id) => http.delete(`/admin/forms/${id}`)
export const publishForm = (id) => http.post(`/admin/forms/${id}/publish`)
export const createFormVersion = (id, version) => http.post(`/admin/forms/${id}/versions`, { version })
export const createFormField = (payload) => http.post('/admin/form-fields', payload)
export const updateFormField = (payload) => http.put('/admin/form-fields', payload)
export const deleteFormField = (id) => http.delete(`/admin/form-fields/${id}`)
export const listAvailableWorkflows = () => http.get('/workflows/available')
export const getWorkflowStartForm = (id) => http.get(`/workflows/${id}/start-form`)
export const startWorkflow = (id, payload) => http.post(`/workflows/${id}/start`, payload)
export const getWorkflowRuntimeForms = (id) => http.get(`/workflow-instances/${id}/forms`)
export const saveWorkflowRuntimeForm = (id, formId, payload) => http.put(`/workflow-instances/${id}/forms/${formId}`, payload)
export const pendingWorkflowTasks = () => http.get('/workflow-tasks/pending')
export const handledWorkflowTasks = () => http.get('/workflow-tasks/handled')
export const initiatedWorkflowInstances = () => http.get('/workflow-instances/initiated')
export const completeWorkflowTask = (id, payload) => http.post(`/workflow-tasks/${id}/complete`, payload)
export const transferWorkflowTask = (id, payload) => http.post(`/workflow-tasks/${id}/transfer`, payload)
export const addSignWorkflowTask = (id, payload) => http.post(`/workflow-tasks/${id}/add-sign`, payload)
export const ccWorkflowTask = (id, payload) => http.post(`/workflow-tasks/${id}/cc`, payload)
export const returnWorkflowTask = (id, payload) => http.post(`/workflow-tasks/${id}/return`, payload)
export const withdrawWorkflowInstance = (id, payload) => http.post(`/workflow-instances/${id}/withdraw`, payload)
export const remindWorkflowTask = (id) => http.post(`/workflow-tasks/${id}/remind`)
export const workflowMonitor = () => http.get('/admin/workflows/monitor')

// Workflow Node Templates
export const listWorkflowNodeTemplates = (params) => http.get(`/admin/workflow-node-templates/list?${qs(params)}`)
export const createWorkflowNodeTemplate = (payload) => http.post('/admin/workflow-node-templates', payload)
export const updateWorkflowNodeTemplate = (payload) => http.put('/admin/workflow-node-templates', payload)
export const deleteWorkflowNodeTemplate = (id) => http.delete(`/admin/workflow-node-templates/${id}`)

export const listWorkflowEdges = (params) => http.get(`/admin/workflow-edges/list?${qs(params)}`)
export const createWorkflowEdge = (payload) => http.post('/admin/workflow-edges', payload)
export const updateWorkflowEdge = (payload) => http.put('/admin/workflow-edges', payload)
export const deleteWorkflowEdge = (id) => http.delete(`/admin/workflow-edges/${id}`)

// Agent Specs
export const listAgentSpecs = (params) => http.get(`/agent/specs/list?${qs(params)}`)
export const agentSpecDetail = (id) => http.get(`/agent/specs/${id}`)
export const agentSpecByCode = (agentCode) => http.get(`/agent/specs/by-code?${qs({ agentCode })}`)
export const createAgentSpec = (payload) => http.post('/agent/specs', payload)
export const updateAgentSpec = (payload) => http.put('/agent/specs', payload)
export const deleteAgentSpec = (id) => http.delete(`/agent/specs/${id}`)
export const refreshAgentSpecs = () => http.post('/agent/specs/refresh')
export const runWorkflowNode = (payload) => http.post('/workflow-node/run', payload)
export const getAgentTrace = (params) => http.get(`/agent/trace?${qs(params)}`)
export const getAgentTraceAssembled = (params) => http.get(`/agent/trace/assembled?${qs(params)}`)

// Workflow Draft
export const saveWorkflowDraft = (payload) => http.post('/workflow-draft/save', payload)
export const getLatestWorkflowDraft = (params) => http.get(`/workflow-draft/latest?${qs(params)}`)
export const publishWorkflowDraft = (payload) => http.post('/workflow-draft/publish', payload)

// Project Assets
export const listProjectRoleAssets = (params) => http.get(`/assets/roles/list?${qs(params)}`)
export const listProjectSceneAssets = (params) => http.get(`/assets/scenes/list?${qs(params)}`)
export const listProjectPropAssets = (params) => http.get(`/assets/props/list?${qs(params)}`)
export const listProjectRelationshipAssets = (params) => http.get(`/assets/relationships/list?${qs(params)}`)

// Skills
export const listSkills = (params) => http.get(`/skill/defs/list?${qs(params)}`)
export const createSkill = (payload) => http.post('/skill/defs', payload)
export const updateSkill = (payload) => http.put('/skill/defs', payload)
export const deleteSkill = (id) => http.delete(`/skill/defs/${id}`)

// Tools
export const listTools = (params) => http.get(`/tool/defs/list?${qs(params)}`)
export const createTool = (payload) => http.post('/tool/defs', payload)
export const updateTool = (payload) => http.put('/tool/defs', payload)
export const deleteTool = (id) => http.delete(`/tool/defs/${id}`)

// Task Logs (执行监控)
export const listTaskLogs = (params) => http.get(`/ai-model/task-logs/list?${qs(params)}`)
export const taskLogDetail = (id) => http.get(`/ai-model/task-logs/${id}`)
export const deleteTaskLog = (id) => http.delete(`/ai-model/task-logs/${id}`)

// Storyboard Prompt Template Profiles
export const listPromptTemplateProfiles = (params) => http.get(`/prompt-template/profiles/list?${qs(params)}`)
export const getPromptTemplateProfile = (id) => http.get(`/prompt-template/profiles/${id}`)
export const createPromptTemplateProfile = (payload) => http.post('/prompt-template/profiles', payload)
export const updatePromptTemplateProfile = (payload) => http.put('/prompt-template/profiles', payload)
export const deletePromptTemplateProfile = (id) => http.delete(`/prompt-template/profiles/${id}`)
