import { http } from './http'

const qs = (params = {}) => {
  const cleaned = Object.fromEntries(
    Object.entries(params).filter(([, v]) => v !== undefined && v !== null && v !== '')
  )
  return new URLSearchParams(cleaned).toString()
}

export const adminLogin = (payload) => http.post('/auth/login', payload)
export const changeOwnPassword = (payload) => http.post('/auth/account/change-password', payload)

export const listUsers = (params) => http.get(`/admin/users/list?${qs(params)}`)
export const userDetail = (id) => http.get(`/admin/users/${id}`)
export const createUser = (payload) => http.post('/admin/users', payload)
export const updateUser = (payload) => http.put('/admin/users', payload)
export const deleteUser = (id) => http.delete(`/admin/users/${id}`)
export const userByEmployee = (employeeId) => http.get(`/admin/users/by-employee/${employeeId}`)
export const unlockUser = (userId) => http.post(`/auth/account/unlock?${qs({ userId })}`)
export const forceLogoutUser = (userId) => http.post(`/auth/account/force-logout?${qs({ userId })}`)
export const resetUserPassword = (userId, newPassword) => http.post('/auth/account/reset-password', { userId, newPassword })

export const portalAdminApplications = () => http.get('/portal/admin/applications')
export const createPortalApplication = (payload) => http.post('/portal/admin/applications', payload)
export const updatePortalApplication = (id, payload) => http.put(`/portal/admin/applications/${id}`, payload)
export const deletePortalApplication = (id) => http.delete(`/portal/admin/applications/${id}`)
export const portalAdminWidgets = () => http.get('/portal/admin/widgets')
export const createPortalWidget = (payload) => http.post('/portal/admin/widgets', payload)
export const updatePortalWidget = (id, payload) => http.put(`/portal/admin/widgets/${id}`, payload)
export const deletePortalWidget = (id) => http.delete(`/portal/admin/widgets/${id}`)

export const listRoles = (params) => http.get(`/admin/roles/list?${qs(params)}`)
export const createRole = (payload) => http.post('/admin/roles/create', payload)
export const updateRole = (payload) => http.put('/admin/roles/update', payload)
export const roleDetail = (id) => http.get(`/admin/roles/${id}/detail`)
export const deleteRole = (id) => http.delete(`/admin/roles/delete/${id}`)

export const listMenus = (params) => http.get(`/admin/menus/list?${qs(params)}`)
export const menuTree = () => http.get('/admin/menus/tree')
export const currentAdminNavigation = () => http.get('/auth/navigation')
export const createMenu = (payload) => http.post('/admin/menus', payload)
export const updateMenu = (payload) => http.put('/admin/menus', payload)
export const deleteMenu = (id) => http.delete(`/admin/menus/${id}`)

export const permissions = (params) => http.get(`/admin/permissions/list?${qs(params)}`)
export const createPermission = (payload) => http.post('/admin/permissions/create', payload)
export const updatePermission = (payload) => http.put('/admin/permissions/update', payload)
export const deletePermission = (id) => http.delete(`/admin/permissions/${id}`)
export const orgList = (params) => http.get(`/admin/organizations/list?${qs(params)}`)
export const orgDetail = (id) => http.get(`/admin/organizations/${id}`)
export const createOrg = (payload) => http.post('/admin/organizations', payload)
export const updateOrg = (payload) => http.put('/admin/organizations', payload)
export const deleteOrg = (id) => http.delete(`/admin/organizations/${id}`)
export const orgImpact = (id) => http.get(`/admin/organizations/${id}/impact`)

export const organizationUnits = (organizationId) => http.get(`/admin/iam/organization-units?${qs({ organizationId })}`)
export const saveOrganizationUnit = (payload) => payload.id
  ? http.put(`/admin/iam/organization-units/${payload.id}`, payload) : http.post('/admin/iam/organization-units', payload)
export const deleteOrganizationUnit = (id) => http.delete(`/admin/iam/organization-units/${id}`)
export const positions = (params) => http.get(`/admin/iam/positions?${qs(params)}`)
export const savePosition = (payload) => payload.id ? http.put(`/admin/iam/positions/${payload.id}`, payload) : http.post('/admin/iam/positions', payload)
export const deletePosition = (id) => http.delete(`/admin/iam/positions/${id}`)
export const jobTitles = () => http.get('/admin/iam/job-titles')
export const saveJobTitle = (payload) => payload.id ? http.put(`/admin/iam/job-titles/${payload.id}`, payload) : http.post('/admin/iam/job-titles', payload)
export const deleteJobTitle = (id) => http.delete(`/admin/iam/job-titles/${id}`)
export const jobLevels = (params) => http.get(`/admin/iam/job-levels?${qs(params)}`)
export const saveJobLevel = (payload) => payload.id ? http.put(`/admin/iam/job-levels/${payload.id}`, payload) : http.post('/admin/iam/job-levels', payload)
export const deleteJobLevel = (id) => http.delete(`/admin/iam/job-levels/${id}`)
export const employees = (params) => http.get(`/admin/iam/employees?${qs(params)}`)
export const saveEmployee = (payload) => payload.id ? http.put(`/admin/iam/employees/${payload.id}`, payload) : http.post('/admin/iam/employees', payload)
export const deleteEmployee = (id) => http.delete(`/admin/iam/employees/${id}`)
export const employeeAssignments = (employeeId) => http.get(`/admin/iam/assignments?${qs({ employeeId })}`)
export const saveEmployeeAssignment = (payload) => payload.id ? http.put(`/admin/iam/assignments/${payload.id}`, payload) : http.post('/admin/iam/assignments', payload)
export const deleteEmployeeAssignment = (id) => http.delete(`/admin/iam/assignments/${id}`)
export const downloadDirectoryImportTemplate = (type) => http.download(`/admin/iam/import/templates/${type}`)
export const importDirectoryData = (type, file, dryRun = false) => { const data = new FormData(); data.append('file', file); return http.upload(`/admin/iam/import/${type}?${qs({ dryRun })}`, data) }

export const dictTree = () => http.get('/admin/dicts/tree')
export const dictListByCode = (dictCode) => http.get(`/admin/dicts/list?${qs({ dictCode })}`)
// 业务页面只读取已配置字典，统一复用无需字典管理权限的只读接口。
// 这样普通教师、教务人员等角色也能正常加载表单下拉选项。
export const dictionaryOptions = async (dictCode) => {
  const response = await http.get(`/dicts/list?${qs({ dictCode })}`)
  return {
    ...response,
    data: (response?.data || []).filter((item) => item.status === 1),
  }
}
export const createDict = (payload) => http.post('/admin/dicts', payload)
export const updateDict = (payload) => http.put('/admin/dicts', payload)
export const deleteDict = (id) => http.delete(`/admin/dicts/${id}`)

export const auditLogs = (params) => http.get(`/admin/audit-logs?${qs(params)}`)
export const exportAuditLogs = (params) => http.download(`/admin/audit-logs/export?${qs(params)}`)

export const customerList = (params) => http.get(`/admin/customers/list?${qs(params)}`)
export const customerDetail = (id) => http.get(`/admin/customers/${id}`)
export const createCustomer = (payload) => http.post('/admin/customers', payload)
export const updateCustomer = (payload) => http.put('/admin/customers', payload)
export const deleteCustomer = (id) => http.delete(`/admin/customers/${id}`)

export const aiModels = (params) => http.get(`/ai-model/models/list?${qs(params)}`)
export const aiModelDetail = (id) => http.get(`/ai-model/models/${id}`)
export const createAiModel = (payload) => http.post('/ai-model/models', payload)
export const updateAiModel = (payload) => http.put('/ai-model/models', payload)
export const deleteAiModel = (id) => http.delete(`/ai-model/models/${id}`)

export const aiApis = (params) => http.get(`/ai-model/apis/list?${qs(params)}`)
export const aiApiDetail = (id) => http.get(`/ai-model/apis/${id}`)
export const createAiApi = (payload) => http.post('/ai-model/apis', payload)
export const updateAiApi = (payload) => http.put('/ai-model/apis', payload)
export const deleteAiApi = (id) => http.delete(`/ai-model/apis/${id}`)

export const aiAccounts = (params) => http.get(`/ai-model/accounts/list?${qs(params)}`)
export const createAiAccount = (payload) => http.post('/ai-model/accounts', payload)
export const updateAiAccount = (payload) => http.put('/ai-model/accounts', payload)
export const deleteAiAccount = (id) => http.delete(`/ai-model/accounts/${id}`)

export const apiParams = (params) => http.get(`/ai-model/api-params/list?${qs(params)}`)
export const createApiParam = (payload) => http.post('/ai-model/api-params', payload)
export const updateApiParam = (payload) => http.put('/ai-model/api-params', payload)
export const deleteApiParam = (id) => http.delete(`/ai-model/api-params/${id}`)

export const listWorkflows = (params) => http.get(`/admin/workflows/list?${qs(params)}`)
export const workflowDetail = (id) => http.get(`/admin/workflows/${id}`)
export const createWorkflow = (payload) => http.post('/admin/workflows', payload)
export const updateWorkflow = (payload) => http.put('/admin/workflows', payload)
export const deleteWorkflow = (id) => http.delete(`/admin/workflows/${id}`)
export const disableWorkflow = (id) => http.post(`/admin/workflows/${id}/disable`)
export const createWorkflowVersion = (id, version) => http.post(`/admin/workflows/${id}/versions`, { version })
export const listWorkflowAcls = (id) => http.get(`/admin/workflows/${id}/acls`)
export const createWorkflowAcl = (id, payload) => http.post(`/admin/workflows/${id}/acls`, payload)
export const deleteWorkflowAcl = (id) => http.delete(`/admin/workflow-acls/${id}`)
export const listWorkflowExecutors = () => http.get('/admin/workflow-executors')
export const validateWorkflow = (id, ai = false) => http.post(`/admin/workflows/${id}/validate?ai=${ai}`)
export const publishWorkflow = (id) => http.post(`/admin/workflows/${id}/publish`)
export const getWorkflowAiSetting = () => http.get('/admin/workflow-ai/settings')
export const updateWorkflowAiSetting = (payload) => http.put('/admin/workflow-ai/settings', payload)
export const createWorkflowByAi = (requirement) => http.post('/admin/workflow-ai/draft', { requirement })

export const listWorkflowNodes = (params) => http.get(`/admin/workflow-nodes/list?${qs(params)}`)
export const createWorkflowNode = (payload) => http.post('/admin/workflow-nodes', payload)
export const getWorkflowByProject = (params) => http.get(`/admin/workflows/by-project?${qs(params)}`)
export const getWorkflowLocks = (params) => http.get(`/admin/workflows/locks?${qs(params)}`)
export const lockWorkflowNode = (payload) => http.post('/admin/workflows/lock', payload)
export const unlockWorkflowNode = (payload) => http.post('/admin/workflows/unlock', payload)
export const updateWorkflowNode = (payload) => http.put('/admin/workflow-nodes', payload)
export const deleteWorkflowNode = (id) => http.delete(`/admin/workflow-nodes/${id}`)

export const listForms = (params) => http.get(`/admin/forms/list?${qs(params)}`)
export const listFormFields = (formId) => http.get(`/admin/form-fields/list?${qs({ formId })}`)
export const createForm = (payload) => http.post('/admin/forms', payload)
export const updateForm = (payload) => http.put('/admin/forms', payload)
export const deleteForm = (id) => http.delete(`/admin/forms/${id}`)
export const publishForm = (id) => http.post(`/admin/forms/${id}/publish`)
export const createFormVersion = (id, version) => http.post(`/admin/forms/${id}/versions`, { version })
export const createFormField = (payload) => http.post('/admin/form-fields', payload)
export const updateFormField = (payload) => http.put('/admin/form-fields', payload)
export const deleteFormField = (id) => http.delete(`/admin/form-fields/${id}`)
export const listAvailableWorkflows = () => http.get('/workflows/available')
export const getWorkflowStartForm = (id) => http.get(`/workflows/${id}/start-form`)
export const startWorkflow = (id, payload) => http.post(`/workflows/${id}/start`, payload)
export const getWorkflowRuntimeForms = (id) => http.get(`/workflow-instances/${id}/forms`)
export const saveWorkflowRuntimeForm = (id, formId, payload) => http.put(`/workflow-instances/${id}/forms/${formId}`, payload)
export const uploadManagedFile = (file, businessType = 'WORKFLOW_FORM_DRAFT', businessId) => {
  const data = new FormData()
  data.append('file', file)
  return http.upload(`/files?${qs({ businessType, businessId })}`, data)
}
export const deleteManagedFile = (id) => http.delete(`/files/${id}`)
export const downloadManagedFile = (id) => http.download(`/files/${id}/content`)
export const pendingWorkflowTasks = (params) => http.get(`/workflow-tasks/pending?${qs(params)}`)
export const handledWorkflowTasks = (params) => http.get(`/workflow-tasks/handled?${qs(params)}`)
export const initiatedWorkflowInstances = (params) => http.get(`/workflow-instances/initiated?${qs(params)}`)
export const completeWorkflowTask = (id, payload) => http.post(`/workflow-tasks/${id}/complete`, payload)
export const rejectWorkflowTask = (id, payload) => http.post(`/workflow-tasks/${id}/reject`, payload)
export const resubmitWorkflowTask = (id, payload) => http.post(`/workflow-tasks/${id}/resubmit`, payload)
export const transferWorkflowTask = (id, payload) => http.post(`/workflow-tasks/${id}/transfer`, payload)
export const addSignWorkflowTask = (id, payload) => http.post(`/workflow-tasks/${id}/add-sign`, payload)
export const ccWorkflowTask = (id, payload) => http.post(`/workflow-tasks/${id}/cc`, payload)
export const returnWorkflowTask = (id, payload) => http.post(`/workflow-tasks/${id}/return`, payload)
export const withdrawWorkflowInstance = (id, payload) => http.post(`/workflow-instances/${id}/withdraw`, payload)
export const remindWorkflowTask = (id) => http.post(`/workflow-tasks/${id}/remind`)
export const remindWorkflowInstance = (id) => http.post(`/workflow-instances/${id}/remind`)
export const claimWorkflowTask = (id) => http.post(`/workflow-tasks/${id}/claim`)
export const unclaimWorkflowTask = (id) => http.post(`/workflow-tasks/${id}/unclaim`)
export const listWorkflowDelegations = (params) => http.get(`/workflow-delegations?${qs(params)}`)
export const createWorkflowDelegation = (payload) => http.post('/workflow-delegations', payload)
export const deleteWorkflowDelegation = (id) => http.delete(`/workflow-delegations/${id}`)
export const listWorkflowNotifications = (params) => http.get(`/workflow-notifications?${qs(params)}`)
export const readWorkflowNotification = (id) => http.post(`/workflow-notifications/${id}/read`)
export const workflowNotificationUnreadCount = () => http.get('/workflow-notifications/unread-count')
export const readAllWorkflowNotifications = () => http.post('/workflow-notifications/read-all')
export const listDeadWorkflowOutbox = (params) => http.get(`/admin/workflow-outbox/dead?${qs(params)}`)
export const retryWorkflowOutbox = (id) => http.post(`/admin/workflow-outbox/${id}/retry`)
export const ignoreWorkflowOutbox = (id) => http.post(`/admin/workflow-outbox/${id}/ignore`)
export const listWorkflowIncidents = (status = 'OPEN', params) => http.get(`/admin/workflow-incidents?${qs({ status, ...params })}`)
export const retryWorkflowIncident = (id) => http.post(`/admin/workflow-incidents/${id}/retry`)
export const skipWorkflowIncident = (id, payload) => http.post(`/admin/workflow-incidents/${id}/skip`, payload)
export const terminateWorkflowIncident = (id, payload) => http.post(`/admin/workflow-incidents/${id}/terminate`, payload)
export const listWorkflowExecutions = (instanceId) => http.get(`/admin/workflow-executions?${qs({ instanceId })}`)
export const workflowMonitor = () => http.get('/admin/workflows/monitor')
export const workflowDirectoryUsers = () => http.get('/workflow-directory/users')

// 通知公告管理
export const listPublications = (params) => http.get(`/admin/publications?${qs(params)}`)
export const publicationDetail = (id) => http.get(`/admin/publications/${id}`)
export const createPublication = (payload) => http.post('/admin/publications', payload)
export const updatePublication = (id, payload) => http.put(`/admin/publications/${id}`, payload)
export const deletePublication = (id) => http.delete(`/admin/publications/${id}`)
export const publishPublication = (id) => http.post(`/admin/publications/${id}/publish`)
export const withdrawPublication = (id) => http.post(`/admin/publications/${id}/withdraw`)
export const submitPublication = (id) => http.post(`/admin/publications/${id}/submit`)
export const approvePublication = (id, comment) => http.post(`/admin/publications/${id}/approve`, { comment })
export const rejectPublication = (id, comment) => http.post(`/admin/publications/${id}/reject`, { comment })
export const publicationStatistics = (id) => http.get(`/admin/publications/${id}/statistics`)
export const publicationVersions = (id) => http.get(`/admin/publications/${id}/versions`)
export const restorePublicationVersion = (id, versionNo) => http.post(`/admin/publications/${id}/versions/${versionNo}/restore`)
export const remindUnreadPublication = (id) => http.post(`/admin/publications/${id}/remind-unread`)
export const uploadPublicationAttachment = (id, file, primaryContent = false) => {
  const data = new FormData()
  data.append('file', file)
  return http.upload(`/admin/publications/${id}/attachments?primaryContent=${primaryContent}`, data)
}
export const downloadAdminPublicationAttachment = (id) => http.download(`/admin/publications/attachments/${id}`)
export const deletePublicationAttachment = (id) => http.delete(`/admin/publications/attachments/${id}`)
export const listNotificationTemplates = (params) => http.get(`/admin/message/templates?${qs(params)}`)
export const createNotificationTemplate = (payload) => http.post('/admin/message/templates', payload)
export const updateNotificationTemplate = (id, payload) => http.put(`/admin/message/templates/${id}`, payload)
export const deleteNotificationTemplate = (id) => http.delete(`/admin/message/templates/${id}`)
export const listNotificationChannelPolicies = () => http.get('/admin/message/channel-policies')
export const saveNotificationChannelPolicy = (channel, payload) => http.put(`/admin/message/channel-policies/${channel}`, payload)
export const notificationMonitor = () => http.get('/admin/message/monitor')
export const listDeadPublicationDeliveries = (params) => http.get(`/admin/message/deliveries/dead?${qs(params)}`)
export const retryPublicationDelivery = (id) => http.post(`/admin/message/deliveries/${id}/retry`)
export const archivePublication = (id, archived = true) => http.post(`/admin/publications/${id}/archive?archived=${archived}`)

// 教育行业：走班排课
export const listCourseOfferings = (semesterCode, params) => http.get(`/admin/education/course-offerings?${qs({ semesterCode, ...params })}`)
export const createCourseOffering = (payload) => http.post('/admin/education/course-offerings', payload)
export const updateCourseOffering = (id, payload) => http.put(`/admin/education/course-offerings/${id}`, payload)
export const deleteCourseOffering = (id) => http.delete(`/admin/education/course-offerings/${id}`)
export const listClassrooms = (params) => http.get(`/admin/education/classrooms?${qs(params)}`)
export const createClassroom = (payload) => http.post('/admin/education/classrooms', payload)
export const updateClassroom = (id, payload) => http.put(`/admin/education/classrooms/${id}`, payload)
export const deleteClassroom = (id) => http.delete(`/admin/education/classrooms/${id}`)
export const listClassSchedule = (semesterCode, dimension = 'ALL', targetId) =>
  http.get(`/admin/education/schedules?${qs({ semesterCode, dimension, targetId })}`)
export const createScheduleEntry = (payload) => http.post('/admin/education/schedules', payload)
export const updateScheduleEntry = (id, payload) => http.put(`/admin/education/schedules/${id}`, payload)
export const deleteScheduleEntry = (id) => http.delete(`/admin/education/schedules/${id}`)
export const listCourseAdjustmentIncidents = (params) =>
  http.get(`/admin/education/course-adjustment-incidents?${qs(params)}`)
export const retryCourseAdjustmentIncident = (id) => http.post(`/admin/education/course-adjustment-incidents/${id}/retry`)
export const batchRetryCourseAdjustmentIncidents = (ids) =>
  http.post('/admin/education/course-adjustment-incidents/batch-retry', { ids })
export const listScheduleVersions = (semesterCode) => http.get(`/admin/education/schedule-versions?${qs({ semesterCode })}`)
export const publishScheduleVersion = (semesterCode) => http.post(`/admin/education/schedule-versions/publish?${qs({ semesterCode })}`)
export const rollbackScheduleVersion = (id) => http.post(`/admin/education/schedule-versions/${id}/rollback`)
export const previewSchedulePublication = (semesterCode) =>
  http.get(`/admin/education/schedule-versions/publication-preview?${qs({ semesterCode })}`)
export const listScheduleCandidates = (semesterCode) =>
  http.get(`/admin/education/schedule-candidates?${qs({ semesterCode })}`)
export const generateScheduleCandidates = (payload) =>
  http.post('/admin/education/schedule-candidates/generate', payload)
export const previewScheduleCandidate = (id) =>
  http.get(`/admin/education/schedule-candidates/${id}/preview`)
export const applyScheduleCandidate = (id) =>
  http.post(`/admin/education/schedule-candidates/${id}/apply`)
export const discardScheduleCandidate = (id) =>
  http.post(`/admin/education/schedule-candidates/${id}/discard`)
export const listAcademicTerms = (params) => http.get(`/admin/education/terms?${qs(params)}`)
export const createAcademicTerm = (payload) => http.post('/admin/education/terms', payload)
export const updateAcademicTerm = (id, payload) => http.put(`/admin/education/terms/${id}`, payload)
export const listEducationGrades = (params) => http.get(`/admin/education/grades?${qs(params)}`)
export const createEducationGrade = (payload) => http.post('/admin/education/grades', payload)
export const updateEducationGrade = (id, payload) => http.put(`/admin/education/grades/${id}`, payload)
export const deleteEducationGrade = (id) => http.delete(`/admin/education/grades/${id}`)
export const listEducationSubjects = (params) => http.get(`/admin/education/subjects?${qs(params)}`)
export const createEducationSubject = (payload) => http.post('/admin/education/subjects', payload)
export const updateEducationSubject = (id, payload) => http.put(`/admin/education/subjects/${id}`, payload)
export const deleteEducationSubject = (id) => http.delete(`/admin/education/subjects/${id}`)
export const listCourseCatalog = (params) => http.get(`/admin/education/courses?${qs(params)}`)
export const createCourseCatalog = (payload) => http.post('/admin/education/courses', payload)
export const updateCourseCatalog = (id, payload) => http.put(`/admin/education/courses/${id}`, payload)
export const listEducationMajors = (params) => http.get(`/admin/education/majors?${qs(params)}`)
export const createEducationMajor = (payload) => http.post('/admin/education/majors', payload)
export const updateEducationMajor = (id, payload) => http.put(`/admin/education/majors/${id}`, payload)
export const deleteEducationMajor = (id) => http.delete(`/admin/education/majors/${id}`)
export const listAdministrativeClasses = (params) => http.get(`/admin/education/administrative-classes?${qs(params)}`)
export const createAdministrativeClass = (payload) => http.post('/admin/education/administrative-classes', payload)
export const updateAdministrativeClass = (id, payload) => http.put(`/admin/education/administrative-classes/${id}`, payload)
export const deleteAdministrativeClass = (id) => http.delete(`/admin/education/administrative-classes/${id}`)
export const listEducationStudents = (params) => http.get(`/admin/education/students?${qs(params)}`)
export const exportEducationStudents = () => http.download('/admin/education/students/export')
export const createEducationStudent = (payload) => http.post('/admin/education/students', payload)
export const updateEducationStudent = (id, payload) => http.put(`/admin/education/students/${id}`, payload)
export const listEducationTeachers = (params) => http.get(`/admin/education/teachers?${qs(params)}`)
export const createEducationTeacher = (payload) => http.post('/admin/education/teachers', payload)
export const updateEducationTeacher = (id, payload) => http.put(`/admin/education/teachers/${id}`, payload)
export const listEducationParents = (params) => http.get(`/admin/education/parents?${qs(params)}`)
export const createEducationParent = (payload) => http.post('/admin/education/parents', payload)
export const updateEducationParent = (id, payload) => http.put(`/admin/education/parents/${id}`, payload)
export const deleteEducationParent = (id) => http.delete(`/admin/education/parents/${id}`)
export const listStudentGuardians = (params) => http.get(`/admin/education/student-guardians?${qs(params)}`)
export const createStudentGuardian = (payload) => http.post('/admin/education/student-guardians', payload)
export const updateStudentGuardian = (id, payload) => http.put(`/admin/education/student-guardians/${id}`, payload)
export const deleteStudentGuardian = (id) => http.delete(`/admin/education/student-guardians/${id}`)
export const listTeachingAssignments = (params) => http.get(`/admin/education/teaching-assignments?${qs(params)}`)
export const createTeachingAssignment = (payload) => http.post('/admin/education/teaching-assignments', payload)
export const updateTeachingAssignment = (id, payload) => http.put(`/admin/education/teaching-assignments/${id}`, payload)
export const deleteTeachingAssignment = (id) => http.delete(`/admin/education/teaching-assignments/${id}`)

// 教育行业：AI 知识库
export const listKnowledgeBases = (params) => http.get(`/admin/knowledge-bases?${qs(params)}`)
export const createKnowledgeBase = (payload) => http.post('/admin/knowledge-bases', payload)
export const updateKnowledgeBase = (id, payload) => http.put(`/admin/knowledge-bases/${id}`, payload)
export const deleteKnowledgeBase = (id) => http.delete(`/admin/knowledge-bases/${id}`)
export const listKnowledgeDocuments = (knowledgeBaseId, params) => (
  http.get(`/admin/knowledge-documents?${qs({ knowledgeBaseId, ...params })}`)
)
export const createKnowledgeTextDocument = (payload) => http.post('/admin/knowledge-documents/text', payload)
export const importKnowledgeDocument = (knowledgeBaseId, title, file) => {
  const data = new FormData()
  data.append('file', file)
  return http.upload(`/admin/knowledge-documents/import?${qs({ knowledgeBaseId, title })}`, data)
}
export const deleteKnowledgeDocument = (id) => http.delete(`/admin/knowledge-documents/${id}`)
export const rebuildKnowledgeDocument = (id) => http.post(`/admin/knowledge-documents/${id}/rebuild`)
export const searchKnowledge = (knowledgeBaseId, keyword, limit = 20) => (
  http.get(`/admin/knowledge-search?${qs({ knowledgeBaseId, keyword, limit })}`)
)
export const askEducationAssistant = (payload) => http.post('/education/ai/assistant/ask', payload)
export const getAiModelStatus = () => http.get('/ai/model/status')
export const listSchedulingAgentProposals = (semesterCode, params) => (
  http.get(`/education/agents/scheduling/proposals?${qs({ semesterCode, ...params })}`)
)
export const createSchedulingAgentProposal = (payload) => http.post('/education/agents/scheduling/proposals', payload)
export const confirmSchedulingAgentProposal = (id) => http.post(`/education/agents/scheduling/proposals/${id}/confirm`)
export const rejectSchedulingAgentProposal = (id) => http.post(`/education/agents/scheduling/proposals/${id}/reject`)
export const analyzeAcademicSchedule = (semesterCode) => (
  http.get(`/education/agents/academic/analyze?${qs({ semesterCode })}`)
)
export const listTeachingClassMembers = (offeringId) => http.get(`/admin/education/teaching-class-members?${qs({ offeringId })}`)
export const enrollTeachingClassStudent = (offeringId, studentId) => http.post(`/admin/education/course-offerings/${offeringId}/enroll`, { studentId })
export const withdrawTeachingClassStudent = (offeringId, studentId) => http.post(`/admin/education/course-offerings/${offeringId}/withdraw`, { studentId })

// Workflow Node Templates
export const listWorkflowNodeTemplates = (params) => http.get(`/admin/workflow-node-templates/list?${qs(params)}`)
export const createWorkflowNodeTemplate = (payload) => http.post('/admin/workflow-node-templates', payload)
export const updateWorkflowNodeTemplate = (payload) => http.put('/admin/workflow-node-templates', payload)
export const deleteWorkflowNodeTemplate = (id) => http.delete(`/admin/workflow-node-templates/${id}`)

export const listWorkflowEdges = (params) => http.get(`/admin/workflow-edges/list?${qs(params)}`)
export const createWorkflowEdge = (payload) => http.post('/admin/workflow-edges', payload)
export const updateWorkflowEdge = (payload) => http.put('/admin/workflow-edges', payload)
export const deleteWorkflowEdge = (id) => http.delete(`/admin/workflow-edges/${id}`)

// Agent Specs
export const listAgentSpecs = (params) => http.get(`/agent/specs/list?${qs(params)}`)
export const agentSpecDetail = (id) => http.get(`/agent/specs/${id}`)
export const agentSpecByCode = (agentCode) => http.get(`/agent/specs/by-code?${qs({ agentCode })}`)
export const createAgentSpec = (payload) => http.post('/agent/specs', payload)
export const updateAgentSpec = (payload) => http.put('/agent/specs', payload)
export const deleteAgentSpec = (id) => http.delete(`/agent/specs/${id}`)
export const refreshAgentSpecs = () => http.post('/agent/specs/refresh')
export const runWorkflowNode = (payload) => http.post('/workflow-node/run', payload)
export const getAgentTrace = (params) => http.get(`/agent/trace?${qs(params)}`)
export const getAgentTraceAssembled = (params) => http.get(`/agent/trace/assembled?${qs(params)}`)

// Workflow Draft
export const saveWorkflowDraft = (payload) => http.post('/workflow-draft/save', payload)
export const getLatestWorkflowDraft = (params) => http.get(`/workflow-draft/latest?${qs(params)}`)
export const publishWorkflowDraft = (payload) => http.post('/workflow-draft/publish', payload)

// Project Assets
export const listProjectRoleAssets = (params) => http.get(`/assets/roles/list?${qs(params)}`)
export const listProjectSceneAssets = (params) => http.get(`/assets/scenes/list?${qs(params)}`)
export const listProjectPropAssets = (params) => http.get(`/assets/props/list?${qs(params)}`)
export const listProjectRelationshipAssets = (params) => http.get(`/assets/relationships/list?${qs(params)}`)

// Skills
export const listSkills = (params) => http.get(`/skill/defs/list?${qs(params)}`)
export const createSkill = (payload) => http.post('/skill/defs', payload)
export const updateSkill = (payload) => http.put('/skill/defs', payload)
export const deleteSkill = (id) => http.delete(`/skill/defs/${id}`)

// Tools
export const listTools = (params) => http.get(`/tool/defs/list?${qs(params)}`)
export const createTool = (payload) => http.post('/tool/defs', payload)
export const updateTool = (payload) => http.put('/tool/defs', payload)
export const deleteTool = (id) => http.delete(`/tool/defs/${id}`)

// Task Logs (执行监控)
export const listTaskLogs = (params) => http.get(`/ai-model/task-logs/list?${qs(params)}`)
export const taskLogDetail = (id) => http.get(`/ai-model/task-logs/${id}`)
export const deleteTaskLog = (id) => http.delete(`/ai-model/task-logs/${id}`)

// Storyboard Prompt Template Profiles
export const listPromptTemplateProfiles = (params) => http.get(`/prompt-template/profiles/list?${qs(params)}`)
export const getPromptTemplateProfile = (id) => http.get(`/prompt-template/profiles/${id}`)
export const createPromptTemplateProfile = (payload) => http.post('/prompt-template/profiles', payload)
export const updatePromptTemplateProfile = (payload) => http.put('/prompt-template/profiles', payload)
export const deletePromptTemplateProfile = (id) => http.delete(`/prompt-template/profiles/${id}`)
