<template>
  <div class="portal-page"><el-page-header @back="$router.push('/portal/tasks')"><template #content><span>{{ bundle?.flow?.flowName || '流程详情' }}</span></template></el-page-header>
    <el-alert v-if="error" :title="error" type="error" show-icon :closable="false" />
    <div v-loading="loading" class="detail-grid" v-if="bundle">
      <main><el-card shadow="never" class="summary"><div><small>业务编号</small><strong>{{ bundle.instance?.businessKey }}</strong></div><div><small>发起人</small><strong>{{ bundle.instance?.initiator }}</strong></div><div><small>当前节点</small><strong>{{ bundle.nodeName }}</strong></div><div><small>状态</small><el-tag :type="statusType(bundle.instance?.status)">{{ statusLabel(bundle.instance?.status) }}</el-tag></div></el-card>
        <el-card v-for="form in bundle.forms||[]" :key="form.formId" shadow="never" class="form-card"><template #header><strong>{{ form.formName }}</strong><el-tag class="role">{{ form.role==='MAIN'?'主表单':'附加表单' }}</el-tag></template><DynamicForm v-model="values[form.formId]" :fields="form.fields" /><div v-if="editable(form)" class="actions"><el-button @click="save(form,true)">保存草稿</el-button><el-button type="primary" @click="save(form,false)">提交表单</el-button></div></el-card>
        <el-empty v-if="!(bundle.forms||[]).length" description="当前节点没有关联表单" />
        <el-card v-if="bundle.currentTask" shadow="never" class="approval"><template #header><strong>{{ bundle.currentTask.taskKind==='STARTER_REWORK'?'修改后重新提交':'审批操作' }}</strong></template><el-input v-model="comment" type="textarea" :rows="3" placeholder="请输入处理意见" /><div class="actions"><el-button v-if="bundle.currentTask.taskKind==='STARTER_REWORK'&&canStart" type="primary" @click="resubmit">重新提交</el-button><template v-else><el-button v-if="canReject&&bundle.operations?.reject!==false" type="danger" @click="reject">拒绝</el-button><el-button v-if="canApprove&&bundle.operations?.approve!==false" type="primary" @click="approve">同意</el-button></template></div></el-card>
      </main>
      <aside><el-card shadow="never"><template #header><strong>流程轨迹</strong></template><el-timeline><el-timeline-item v-for="item in bundle.history||[]" :key="item.id" :timestamp="item.completedAt||item.createTime" :type="historyType(item.status)"><strong>{{ item.nodeName }}</strong><p>{{ item.assignee }} · {{ taskStatus(item.status) }}</p><small v-if="item.comment">{{ item.comment }}</small></el-timeline-item></el-timeline><el-empty v-if="!(bundle.history||[]).length" description="暂无审批记录" /></el-card></aside>
    </div>
  </div>
</template>
<script setup>
import { onMounted,ref } from 'vue';import { useRoute,useRouter } from 'vue-router';import { ElMessage } from 'element-plus';import DynamicForm from '../components/DynamicForm.vue';import { getWorkflowRuntimeForms,saveWorkflowRuntimeForm,completeWorkflowTask,rejectWorkflowTask,resubmitWorkflowTask } from '../../../api/admin';import { hasAdminPermission } from '../../../store/auth'
const route=useRoute(),router=useRouter(),bundle=ref(null),values=ref({}),loading=ref(false),error=ref(''),comment=ref('')
const canApprove=hasAdminPermission('workflow:task:approve'),canReject=hasAdminPermission('workflow:task:reject'),canStart=hasAdminPermission('workflow:instance:start')
const load=async()=>{loading.value=true;error.value='';try{const res=await getWorkflowRuntimeForms(route.params.id);bundle.value=res?.data;(bundle.value?.forms||[]).forEach(f=>{values.value[f.formId]={...(f.data||{})}})}catch(e){error.value=`流程详情加载失败：${e?.message||'请求失败'}`}finally{loading.value=false}}
const editable=form=>bundle.value?.canEdit&&(form.fields||[]).some(f=>f.permission==='EDIT')
const editableData=form=>Object.fromEntries((form.fields||[]).filter(f=>f.permission==='EDIT').map(f=>[f.fieldKey,values.value[form.formId]?.[f.fieldKey]]))
const save=async(form,draft)=>{await saveWorkflowRuntimeForm(route.params.id,form.formId,{data:editableData(form),draft});ElMessage.success(draft?'草稿已保存':'表单已提交');await load()}
const approve=async()=>{for(const form of bundle.value.forms||[])if(editable(form))await saveWorkflowRuntimeForm(route.params.id,form.formId,{data:editableData(form),draft:false});await completeWorkflowTask(bundle.value.currentTask.id,{approved:true,comment:comment.value});ElMessage.success('审批已通过');router.push('/portal/tasks')}
const reject=async()=>{if(bundle.value.currentTask.rejectPolicy==='SELECTABLE')return ElMessage.warning('请选择从任务中心执行拒绝并指定退回节点');await rejectWorkflowTask(bundle.value.currentTask.id,{comment:comment.value});ElMessage.success('拒绝处理完成');router.push('/portal/tasks')}
const resubmit=async()=>{for(const form of bundle.value.forms||[])if(editable(form))await saveWorkflowRuntimeForm(route.params.id,form.formId,{data:editableData(form),draft:false});await resubmitWorkflowTask(bundle.value.currentTask.id,{comment:comment.value});ElMessage.success('已重新提交');router.push('/portal/tasks')}
const statusLabel=s=>({RUNNING:'审批中',COMPLETED:'已完成',REJECTED:'已拒绝',WITHDRAWN:'已撤回'}[s]||s),statusType=s=>({COMPLETED:'success',REJECTED:'danger',WITHDRAWN:'info',RUNNING:'warning'}[s]||'info')
const taskStatus=s=>({PENDING:'待处理',APPROVED:'已通过',REJECTED:'已拒绝',CANCELLED:'已取消',CC:'已抄送'}[s]||s),historyType=s=>({APPROVED:'success',REJECTED:'danger',PENDING:'primary',CANCELLED:'info',CC:'warning'}[s]||'info')
onMounted(load)
</script>
<style scoped>.detail-grid{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:18px}.summary{margin-bottom:16px}.summary :deep(.el-card__body){display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.summary div{display:flex;flex-direction:column;gap:7px}.summary small{color:#8492a6}.form-card,.approval{margin-bottom:16px}.role{margin-left:10px}.actions{text-align:right;margin-top:16px}.el-timeline p{margin:4px 0;color:#64748b}.el-timeline small{color:#8492a6}@media(max-width:1000px){.detail-grid{grid-template-columns:1fr}.summary :deep(.el-card__body){grid-template-columns:repeat(2,1fr)}}</style>
